#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Customers\_SingleSiteRow.cshtml"
    using Maestro.Common.Extensions;
    
    #line default
    #line hidden
    using Maestro.Web;
    using Maestro.Web.Controls;
    using Maestro.Web.Resources;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Customers/_SingleSiteRow.cshtml")]
    public partial class _Views_Customers__SingleSiteRow_cshtml : Maestro.Web.BaseViewPage<Maestro.Web.Models.Customers.SingleSiteViewModel>
    {
        public _Views_Customers__SingleSiteRow_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Customers\_SingleSiteRow.cshtml"
 if (Model != null && Model.Website != null)
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"row user-item customer-item\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-sm-4 ci-customer-name\"");

WriteAttribute("search-value", Tuple.Create(" search-value=\"", 235), Tuple.Create("\"", 261)
            
            #line 7 "..\..\Views\Customers\_SingleSiteRow.cshtml"
, Tuple.Create(Tuple.Create("", 250), Tuple.Create<System.Object, System.Int32>(Model.Name
            
            #line default
            #line hidden
, 250), false)
);

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 8 "..\..\Views\Customers\_SingleSiteRow.cshtml"
       Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"col-sm-4 ci-site-name\"");

WriteAttribute("search-value", Tuple.Create(" search-value=\"", 348), Tuple.Create("\"", 382)
            
            #line 10 "..\..\Views\Customers\_SingleSiteRow.cshtml"
, Tuple.Create(Tuple.Create("", 363), Tuple.Create<System.Object, System.Int32>(Model.Website.Name
            
            #line default
            #line hidden
, 363), false)
);

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 11 "..\..\Views\Customers\_SingleSiteRow.cshtml"
       Write(Model.Website.Name);

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"col-sm-2 ci-site-state\"");

WriteLiteral(">\r\n            <strong>");

            
            #line 14 "..\..\Views\Customers\_SingleSiteRow.cshtml"
               Write(Model.Website.IsActive.ToStateString());

            
            #line default
            #line hidden
WriteLiteral("</strong>\r\n\r\n");

            
            #line 16 "..\..\Views\Customers\_SingleSiteRow.cshtml"
            
            
            #line default
            #line hidden
            
            #line 16 "..\..\Views\Customers\_SingleSiteRow.cshtml"
             if (!Model.Website.IsPublished)
            {

            
            #line default
            #line hidden
WriteLiteral("                <span");

WriteLiteral(" class=\"text-danger\"");

WriteLiteral(">Not Published</span>\r\n");

            
            #line 19 "..\..\Views\Customers\_SingleSiteRow.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"col-sm-2 ci-site-edit\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 23 "..\..\Views\Customers\_SingleSiteRow.cshtml"
       Write(Html.CustomerActionLink("Edit", Model.Subdomain, "General", "Settings"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n");

            
            #line 26 "..\..\Views\Customers\_SingleSiteRow.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
