#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Maestro.Web;
    using Maestro.Web.Controls;
    using Maestro.Web.Resources;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Customers/CreateCustomer.cshtml")]
    public partial class _Views_Customers_CreateCustomer_cshtml : Maestro.Web.BaseViewPage<Maestro.Web.Models.Customers.CreateCustomerViewModel>
    {
        public _Views_Customers_CreateCustomer_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"modal fade\"");

WriteLiteral(" id=\"create-customer\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\r\n                <h4");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(">");

            
            #line 7 "..\..\Views\Customers\CreateCustomer.cshtml"
                                   Write(GlobalStrings.Create_Customer_CreateCustomerText);

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n            </div> \r\n\r\n");

            
            #line 10 "..\..\Views\Customers\CreateCustomer.cshtml"
            
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\Customers\CreateCustomer.cshtml"
             using (Html.BeginForm("Create", "Customers", FormMethod.Post, new { id="create-customer-form"}))
            {

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">               \r\n                    <h5><strong>");

            
            #line 13 "..\..\Views\Customers\CreateCustomer.cshtml"
                           Write(GlobalStrings.Create_Customer_Step1Text);

            
            #line default
            #line hidden
WriteLiteral("</strong></h5>\r\n                    <p>");

            
            #line 14 "..\..\Views\Customers\CreateCustomer.cshtml"
                  Write(GlobalStrings.Create_Customer_CustomerNameFieldTip);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-sm-4 ci-text\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 17 "..\..\Views\Customers\CreateCustomer.cshtml"
                       Write(Html.LabelFor(model => model.CustomerName));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"col-sm-8\"");

WriteLiteral(">\r\n\r\n");

WriteLiteral("                            ");

            
            #line 21 "..\..\Views\Customers\CreateCustomer.cshtml"
                       Write(Html.TextBoxFor(model => model.CustomerName));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <div");

WriteLiteral(" class=\"input-sub-note x-small error-state\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 23 "..\..\Views\Customers\CreateCustomer.cshtml"
                           Write(Html.ValidationMessageFor(model => model.CustomerName));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                        </div>\r\n           " +
"         </div>\r\n                    <h5><strong>");

            
            #line 27 "..\..\Views\Customers\CreateCustomer.cshtml"
                           Write(GlobalStrings.Create_Customer_Step2Text);

            
            #line default
            #line hidden
WriteLiteral("</strong></h5>\r\n                    <p>");

            
            #line 28 "..\..\Views\Customers\CreateCustomer.cshtml"
                  Write(GlobalStrings.Create_Customer_SubdomainNameFieldTip);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                    <p><strong>");

            
            #line 29 "..\..\Views\Customers\CreateCustomer.cshtml"
                          Write(GlobalStrings.Create_Customer_ExampleText);

            
            #line default
            #line hidden
WriteLiteral("</strong><br />https://www.<strong>customername</strong>.healthharmonymaestro.com" +
"</p>\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-sm-4 ci-text\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 32 "..\..\Views\Customers\CreateCustomer.cshtml"
                       Write(Html.LabelFor(model => model.SubdomainName));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"col-sm-8\"");

WriteLiteral(">\r\n      \r\n");

WriteLiteral("                            ");

            
            #line 36 "..\..\Views\Customers\CreateCustomer.cshtml"
                       Write(Html.TextBoxFor(model => model.SubdomainName));

            
            #line default
            #line hidden
WriteLiteral("         \r\n                            <div");

WriteLiteral(" class=\"input-sub-note x-small error-state\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 38 "..\..\Views\Customers\CreateCustomer.cshtml"
                           Write(Html.ValidationMessageFor(model => model.SubdomainName));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                        </div>\r\n           " +
"         </div>\r\n                    <h5><strong>");

            
            #line 42 "..\..\Views\Customers\CreateCustomer.cshtml"
                           Write(GlobalStrings.Create_Customer_Spet3Text);

            
            #line default
            #line hidden
WriteLiteral("</strong></h5>\r\n                    <p>");

            
            #line 43 "..\..\Views\Customers\CreateCustomer.cshtml"
                  Write(GlobalStrings.Create_Customer_SiteNameFieldTip);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-sm-4 ci-text\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 46 "..\..\Views\Customers\CreateCustomer.cshtml"
                       Write(Html.LabelFor(model => model.FirstSiteName));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"col-sm-8\"");

WriteLiteral(">\r\n                          \r\n");

WriteLiteral("                            ");

            
            #line 50 "..\..\Views\Customers\CreateCustomer.cshtml"
                       Write(Html.TextBoxFor(model => model.FirstSiteName));

            
            #line default
            #line hidden
WriteLiteral("                            \r\n                            <div");

WriteLiteral(" class=\"input-sub-note x-small error-state\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 52 "..\..\Views\Customers\CreateCustomer.cshtml"
                           Write(Html.ValidationMessageFor(model => model.FirstSiteName));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                        </div>\r\n           " +
"         </div>\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">                        \r\n                        <div");

WriteLiteral(" class=\"col-sm-4 ci-text\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 58 "..\..\Views\Customers\CreateCustomer.cshtml"
                       Write(Html.LabelFor(model => model.ContactPhone));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"col-sm-8\"");

WriteLiteral(">\r\n\r\n");

WriteLiteral("                            ");

            
            #line 62 "..\..\Views\Customers\CreateCustomer.cshtml"
                       Write(Html.TextBoxFor(model => model.ContactPhone));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <div");

WriteLiteral(" class=\"input-sub-note x-small error-state\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 64 "..\..\Views\Customers\CreateCustomer.cshtml"
                           Write(Html.ValidationMessageFor(model => model.ContactPhone));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                        </div>\r\n           " +
"         </div>\r\n                    <p><em>");

            
            #line 68 "..\..\Views\Customers\CreateCustomer.cshtml"
                      Write(GlobalStrings.RequiredText);

            
            #line default
            #line hidden
WriteLiteral("</em></p>\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-xs-10 error-state\"");

WriteLiteral(" id=\"server-error-message\"");

WriteLiteral(">\r\n\r\n                          \r\n                        </div>\r\n                " +
"    </div>\r\n                </div>\r\n");

WriteLiteral("                <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\r\n\r\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" id=\"cancel-button\"");

WriteLiteral(">");

            
            #line 78 "..\..\Views\Customers\CreateCustomer.cshtml"
                                                                                                     Write(GlobalStrings.Edit_Customer_CancelButtonText);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(" id=\"submit-customer\"");

WriteLiteral(">");

            
            #line 79 "..\..\Views\Customers\CreateCustomer.cshtml"
                                                                                  Write(GlobalStrings.Edit_Customer_SaveButtonText);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                </div>\r\n");

            
            #line 81 "..\..\Views\Customers\CreateCustomer.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
