#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Maestro.Common.Extensions;
    using Maestro.Web;
    using Maestro.Web.Areas.Customer;
    using Maestro.Web.Controls;
    using Maestro.Web.Resources;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Customer/Views/CareBuilder/Templates/ProtocolsAndPrograms/ProgramProtocol" +
        "Template.cshtml")]
    public partial class _Areas_Customer_Views_CareBuilder_Templates_ProtocolsAndPrograms_ProgramProtocolTemplate_cshtml : Maestro.Web.BaseViewPage<dynamic>
    {
        public _Areas_Customer_Views_CareBuilder_Templates_ProtocolsAndPrograms_ProgramProtocolTemplate_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" id=\"programProtocolTemplate\"");

WriteLiteral(" type=\"text/template\"");

WriteLiteral(@">
    <div class=""dropdown"">
        <span id=""programProtocol_<%= id %>"" title=""<%= name.value %>""
                class=""protocol-item dropdown-toggle""
                data-toggle=""dropdown""
                aria-haspopup=""true""
                aria-expanded=""false""
                type=""button"">
            <% if (recurrenceId !== null) { %>
                <i class=""recurrence-status""></i>
            <% } %>
            <%= name.value %>
        </span>
        <ul class=""dropdown-menu"" aria-labelledby=""programProtocol_<%= id %>"">
            <% if (recurrenceId === null) { %>
                <li><a class=""js-set-recurrence"">Set Recurrence</a></li>
                <li><a class=""js-delete-protocol"">Delete Protocol</a></li>
            <% } else { %>
                <li><a class=""js-edit-recurrence"">Edit Recurrence</a></li>
                <li><a class=""js-delete-protocol-occurence"">Delete Protocol Occurrence</a></li>
                <li><a class=""js-delete-protocol-series"">Delete Protocol Series</a></li>
            <% } %>
        </ul>
    </div>
</script>");

        }
    }
}
#pragma warning restore 1591
