#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Maestro.Common.Extensions;
    using Maestro.Web;
    using Maestro.Web.Areas.Customer;
    using Maestro.Web.Controls;
    using Maestro.Web.Resources;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Customer/Views/CareBuilder/Templates/ProtocolsAndPrograms/ProtocolTreeAns" +
        "werChoiceItemTemplate.cshtml")]
    public partial class _Areas_Customer_Views_CareBuilder_Templates_ProtocolsAndPrograms_ProtocolTreeAnswerChoiceItemTemplate_cshtml : Maestro.Web.BaseViewPage<dynamic>
    {
        public _Areas_Customer_Views_CareBuilder_Templates_ProtocolsAndPrograms_ProtocolTreeAnswerChoiceItemTemplate_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" id=\"protocolTreeAnswerChoiceItemTemplate\"");

WriteLiteral(" type=\"text/template\"");

WriteLiteral(">\r\n    <div class=\"protocol-item-element protocol-item-element-answer <% if ( isM" +
"ultipleChoice ) { %>js-branching-prohibited<% } %>\" data-branchId=\"<%= branchId " +
"%>\">\r\n        <div id=\"answer-alert-icon-<%=id%>-at-question-<%=elementId%>\" cla" +
"ss=\"pull-right element-alert\">\r\n            <span class=\"glyphicon glyphicon-bel" +
"l\"></span>\r\n        </div>\r\n\r\n        <%=answerString.value%>\r\n        <div clas" +
"s=\"dropdown element-settings\">\r\n            <button class=\"btn btn-default btn-s" +
"ettings dropdown-toggle\" type=\"button\" id=\"answer-settings-<%=elementId%>\" data-" +
"toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n                <" +
"span class=\"glyphicon glyphicon-cog\"></span>\r\n            </button>\r\n           " +
" <ul id=\"settings-answer-<%=id%>-at-question-<%=elementId%>\" \r\n                c" +
"lass=\"dropdown-menu dropdown-menu-right\" \r\n                aria-labelledby=\"answ" +
"er-settings-<%=elementId%>\">\r\n\r\n                <li>\r\n                    <a cla" +
"ss=\"js-is-ended js-is-ended-branch <% if ( nextProtocolElementId == null ) { %>p" +
"rotocol-set-continue<% }else{ %>protocol-set-end<% } %>\"\r\n                      " +
" data-branchId=\"<%=branchId%>\"\r\n                       data-elementId=\"<%=elemen" +
"tId%>\">\r\n                        <% if ( nextProtocolElementId == null ) { %>Con" +
"tinue Protocol <% }else{ %>End Protocol<% } %>\r\n                    </a>\r\n      " +
"          </li>\r\n                <li class=\"js-unset-alert-li\">\r\n               " +
"     <a class=\"js-unset-alert\" data-question-id=\"<%=elementId%>\" data-answer-id=" +
"\"<%=id%>\">\r\n                        Unset Alert\r\n                    </a>\r\n     " +
"           </li>\r\n                \r\n                <% if ( alertSeverities.leng" +
"th ) { %>\r\n                    <% _.each(alertSeverities, function(alertSeverity" +
"){ %>\r\n                        <li class=\"js-set-alert-li\">\r\n                   " +
"         <a class=\"js-set-alert\" \r\n                               data-question-" +
"id=\"<%=elementId%>\" \r\n                               data-answer-id=\"<%=id%>\"\r\n " +
"                              data-alert-severity-id=\"<%= alertSeverity.id %>\">\r" +
"\n                                Set <%= alertSeverity.name %> Alert\r\n          " +
"                  </a>\r\n                        </li>\r\n                    <% })" +
"; %>\r\n                <% }else{ %>\r\n                    <li class=\"js-set-alert-" +
"li\">\r\n                        <a class=\"js-set-alert\"\r\n                         " +
"  data-question-id=\"<%=elementId%>\"\r\n                           data-answer-id=\"" +
"<%=id%>\">\r\n                            Set Alert\r\n                        </a>\r\n" +
"                    </li>\r\n                <% } %>\r\n            </ul>\r\n        <" +
"/div>\r\n        \r\n        <% if (nextProtocolElementId == null ) { %>\r\n          " +
"  <span class=\"element-status glyphicon glyphicon-remove-circle\"></span>\r\n      " +
"  <% } %>\r\n    </div>\r\n</script>");

        }
    }
}
#pragma warning restore 1591
