#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Maestro.Common.Extensions;
    using Maestro.Web;
    using Maestro.Web.Areas.Customer;
    using Maestro.Web.Controls;
    using Maestro.Web.Resources;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Customer/Views/CareBuilder/Templates/ProtocolsAndPrograms/ProtocolTreeQue" +
        "stionItemTemplate.cshtml")]
    public partial class _Areas_Customer_Views_CareBuilder_Templates_ProtocolsAndPrograms_ProtocolTreeQuestionItemTemplate_cshtml : Maestro.Web.BaseViewPage<dynamic>
    {
        public _Areas_Customer_Views_CareBuilder_Templates_ProtocolsAndPrograms_ProtocolTreeQuestionItemTemplate_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" id=\"protocolTreeQuestionItemTemplate\"");

WriteLiteral(" type=\"text/template\"");

WriteLiteral(@">
    <div class=""protocol-item-element protocol-item-element-question protocol-item-element-<% if ( element.type == 2 ) { %>textandmedia<% }else if ( element.type == 3 ){ %>measurement<% }else if ( element.type == 4 ){ %>assessment<% }else {%>question<% } %>""
         data-isMainBranch=""<%= isMainBranch %>"">
        <% if( element.type == 2 ) { %>
            <% if( element.text ) { %>
                <p><%=element.text.value%></p>
            <% } %>
            <% if( element.media ) { %>
                <div class=""media media-preview-ci"">
                    <div class=""media-left media-middle"">
                        <% if( element.media.contentType.match('image') ) { %>
                            <img src=""<%=element.media.thumbnailUrl%>"" class=""thumbnail thumbnail-ci thumbnail-protocol-ci"" alt="""">
                        <% } else { %>
                            <span class=""glyphicon glyphicon-file""></span>
                        <% } %>
                    </div>
                    <div class=""media-body"">
                        <p class=""strong""><%=element.media.name%></p>
                        <p><%=element.media.description%></p>
                    </div>
                </div>
            <% } %>
        <% } else { %>
            <%=element.questionElementString.value%>
        
            <% if (element.answerSet && element.answerSet.isMultipleChoice) { %>
                <br />");

            
            #line 27 "..\..\Areas\Customer\Views\CareBuilder\Templates\ProtocolsAndPrograms\ProtocolTreeQuestionItemTemplate.cshtml"
                 Write(Html.Partial("_MultiSelectLabel"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <% } %>\r\n        <% } %>\r\n        <% if ( element.type == 1 ) { %><" +
"a class=\"btn-toggle-answers\">Hide Answers</a><% } %>\r\n        <div class=\"dropdo" +
"wn element-settings\">\r\n            <button class=\"btn btn-default btn-settings d" +
"ropdown-toggle\" type=\"button\" id=\"element-settings-<%=id%>\" data-toggle=\"dropdow" +
"n\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n                <span class=\"gly" +
"phicon glyphicon-cog\"></span>\r\n            </button>\r\n            <ul class=\"dro" +
"pdown-menu dropdown-menu-right\" aria-labelledby=\"element-settings-<%=id%>\">\r\n   " +
"             <% if ( !isMainBranch && !branches.length ) { %>\r\n                 " +
"   <li><a class=\"js-is-ended js-is-ended-element <% if ( nextProtocolElementId =" +
"= null ) { %>protocol-set-continue<% }else{ %>protocol-set-end<% } %>\" data-elem" +
"entid=\"<%=id%>\"><% if ( nextProtocolElementId == null ) { %>Continue Protocol <%" +
" }else{ %>End Protocol<% } %></a></li>\r\n                <% } %>\r\n               " +
" <li><a class=\"js-delete-element\" data-elementid=\"<%=id%>\">Delete Element</a></l" +
"i>\r\n            </ul>\r\n        </div>\r\n\r\n        <% if ( !isMainBranch && !branc" +
"hes.length && nextProtocolElementId == null ) { %>\r\n            <span class=\"ele" +
"ment-status glyphicon glyphicon-remove-circle\"></span>\r\n        <% } %>\r\n    </d" +
"iv>\r\n    <ol id=\"<%=id%>-container\" class=\"protocol-list\"></ol>\r\n    <% if ( ele" +
"ment.type == 3 ) { %>\r\n        <p>\r\n            New Measurement Branch\r\n        " +
"    <button type=\"button\" class=\"js-add-measurement-branch\" \r\n                  " +
"  data-measurement-type=\"<%=element.measurementType%>\"\r\n                    data" +
"-measurement-name=\"<%=element.questionElementString.value%>\"\r\n                  " +
"  data-elementId=\"<%=id%>\">Add</button>\r\n        </p>\r\n    <% } %>\r\n</script>");

        }
    }
}
#pragma warning restore 1591
