#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Maestro.Common.Extensions;
    using Maestro.Web;
    using Maestro.Web.Areas.Customer;
    using Maestro.Web.Controls;
    using Maestro.Web.Resources;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Customer/Views/CareBuilder/Templates/ProtocolsAndPrograms/ProtocolSimulat" +
        "orTemplate.cshtml")]
    public partial class _Areas_Customer_Views_CareBuilder_Templates_ProtocolsAndPrograms_ProtocolSimulatorTemplate_cshtml : Maestro.Web.BaseViewPage<dynamic>
    {
        public _Areas_Customer_Views_CareBuilder_Templates_ProtocolsAndPrograms_ProtocolSimulatorTemplate_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" id=\"protocolSimulatorTemplate\"");

WriteLiteral(" type=\"text/template\"");

WriteLiteral(@">
    <header class=""header-simulator clearfix"">
        <div class=""header-home pull-left"">
            <a>
                <i class=""fa fa-home""></i><br>
                Home
            </a>
        </div>
        <div class=""hh-logo pull-right"">
            <a href=""#"">
                <img src=""/Content/img/logo-hh-simulator.png"" width=""184"" height=""40"" alt="""" >  
            </a>
            <i class=""fa fa-wifi""></i>
        </div>
    </header>
    <section class=""simulator-content clearfix"">
        <div class=""simulator-content-question pull-left"">
            <div class=""question-text""></div>
            <div class=""question-nav""></div>
        </div>
        <div class=""simulator-content-answer pull-right""></div>
    </section>
</script>");

        }
    }
}
#pragma warning restore 1591
