#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Maestro.Common.Extensions;
    using Maestro.Web;
    using Maestro.Web.Areas.Customer;
    using Maestro.Web.Controls;
    using Maestro.Web.Resources;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Customer/Views/CareBuilder/Templates/ProtocolsAndPrograms/ProtocolTextMed" +
        "iaElementListItemTemplate.cshtml")]
    public partial class _Areas_Customer_Views_CareBuilder_Templates_ProtocolsAndPrograms_ProtocolTextMediaElementListItemTemplate_cshtml : Maestro.Web.BaseViewPage<dynamic>
    {
        public _Areas_Customer_Views_CareBuilder_Templates_ProtocolsAndPrograms_ProtocolTextMediaElementListItemTemplate_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" id=\"protocolTextMediaElementListItemTemplate\"");

WriteLiteral(" type=\"text/template\"");

WriteLiteral(">\r\n    <div class=\"protocol-search-element-title protocol-handle clearfix\">\r\n    " +
"    <div class=\"pull-left italic\">Text and media</div>\r\n        <span class=\"gly" +
"phicon glyphicon-move pull-right handle-icon\"></span>\r\n    </div>\r\n    <div clas" +
"s=\"protocol-search-element-body\">\r\n        <p class=\"search-result-text strong\" " +
"title=\"<%=name%>\"><%=name%></p>\r\n        <% if( typeof(text) !== \"undefined\" ) {" +
" %>\r\n        <p class=\"search-result-text\"><%=text%></p>\r\n        <% } %>\r\n     " +
"   \r\n        <% if( typeof(thumbnailUrl) !== \"undefined\" && thumbnailUrl ) { %>\r" +
"\n            <div class=\"media media-preview-ci\">\r\n                <div class=\"m" +
"edia-left media-middle protocol-search-text-media-img\">\r\n                    <% " +
"if( mediaType == 1 ) { %>\r\n                        <img src=\"<%=thumbnailUrl%>\" " +
"alt=\"\" class=\"thumbnail thumbnail-ci\">\r\n                    <% } else { %>\r\n    " +
"                    <span class=\"glyphicon glyphicon-file\"></span>\r\n            " +
"        <% } %>\r\n                </div>\r\n                <div class=\"media-body\"" +
">\r\n                    <% if( typeof(imageName) !== \"undefined\" ) { %>\r\n        " +
"                <p><%=imageName%></p>\r\n                    <% } %>\r\n            " +
"        <% if( typeof(description) !== \"undefined\" ) { %>\r\n                     " +
"   <p><%=description%></p>\r\n                    <% } %>\r\n                </div>\r" +
"\n            </div>\r\n        <% } %>\r\n        <% if( tags.length > 0 ) { %>\r\n   " +
"         <div class=\"search-result-tags\">\r\n                <% _.each(tags, funct" +
"ion(tag){ %>\r\n                <span class=\"label label-info\" title=\"<%= tag %>\">" +
"<%= tag %></span>\r\n                <% }); %>\r\n            </div>\r\n        <% } %" +
">\r\n    </div>\r\n</script>");

        }
    }
}
#pragma warning restore 1591
