#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Maestro.Common.Extensions;
    using Maestro.Web;
    using Maestro.Web.Areas.Customer;
    using Maestro.Web.Controls;
    using Maestro.Web.Resources;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Customer/Views/CareBuilder/Templates/ProtocolsAndPrograms/ProtocolTreeAns" +
        "werScaleItemTemplate.cshtml")]
    public partial class _Areas_Customer_Views_CareBuilder_Templates_ProtocolsAndPrograms_ProtocolTreeAnswerScaleItemTemplate_cshtml : Maestro.Web.BaseViewPage<dynamic>
    {
        public _Areas_Customer_Views_CareBuilder_Templates_ProtocolsAndPrograms_ProtocolTreeAnswerScaleItemTemplate_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" id=\"protocolTreeAnswerScaleItemTemplate\"");

WriteLiteral(" type=\"text/template\"");

WriteLiteral(">\r\n\t<div class=\"protocol-item-element protocol-item-element-answer protocol-item-" +
"disabled\">\r\n\t\t<div class=\"row hide-grid-ci\">\r\n\t\t\t<div class=\"col-sm-1\"></div>\r\n\t" +
"\t\t<div class=\"col-sm-10 offset-0\">\r\n\t\t\t\t<div class=\"clearfix\">\r\n\t\t\t\t\t<span class" +
"=\"pull-left scale-answer-label min\"><%=lowLabel.value%></span>\r\n\t\t\t\t\t<span class" +
"=\"pull-right scale-answer-label max\"><%=highLabel.value%></span>\r\n\t\t\t\t\t<% if (mi" +
"dLabel != null) { %>\r\n\t\t\t\t\t    <span class=\"pull-center scale-answer-label mid\">" +
"<%= midLabel.value %></span>\r\n\t\t\t\t\t<% } %>\r\n\t\t\t\t</div>\r\n\t\t\t</div>\r\n\t\t\t<div class" +
"=\"col-sm-1\"></div>\r\n\t\t</div>\r\n\t\t<div class=\"row hide-grid-ci\">\r\n\t\t\t<div class=\"c" +
"ol-sm-1 text-right\"><%=lowValue%></div>\r\n\t\t\t<div class=\"col-sm-10 offset-0\">\r\n\t\t" +
"\t\t <input class=\"scale\" type=\"text\" data-slider-min=\"<%=lowValue%>\" data-slider-" +
"max=\"<%=highValue%>\" data-slider-step=\"1\" data-slider-value=\"0\"/>\r\n\t\t\t</div>\r\n\t\t" +
"\t<div class=\"col-sm-1\"><%=highValue%></div>\r\n\t\t</div>\r\n\t\t<div class=\"dropdown el" +
"ement-settings\">\r\n\t\t\t<!--button class=\"btn btn-default btn-settings dropdown-tog" +
"gle\" type=\"button\" id=\"element-settings-<%=id%>\" data-toggle=\"dropdown\" aria-has" +
"popup=\"true\" aria-expanded=\"false\">\r\n\t\t\t\t<span class=\"glyphicon glyphicon-cog\"><" +
"/span>\r\n\t\t\t</button>\r\n\t\t\t<ul class=\"dropdown-menu\" aria-labelledby=\"element-sett" +
"ings-<%=id%>\">\r\n\t\t\t\t<li><a href=\"#\">Action</a></li>\r\n\t\t\t\t<li><a href=\"#\">Another" +
" action</a></li>\r\n\t\t\t\t<li><a href=\"#\">Something else here</a></li>\r\n\t\t\t\t<li><a h" +
"ref=\"#\">Separated link</a></li>\r\n\t\t\t</ul-->\r\n\t\t</div>\r\n\t</div>\r\n</script>");

        }
    }
}
#pragma warning restore 1591
