#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Maestro.Common.Extensions;
    using Maestro.Web;
    using Maestro.Web.Areas.Customer;
    using Maestro.Web.Controls;
    using Maestro.Web.Resources;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Customer/Views/Settings/Templates/ConditionDetailsView.cshtml")]
    public partial class _Areas_Customer_Views_Settings_Templates_ConditionDetailsView_cshtml : Maestro.Web.BaseViewPage<dynamic>
    {
        public _Areas_Customer_Views_Settings_Templates_ConditionDetailsView_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" id=\"conditionDetailsView\"");

WriteLiteral(" type=\"text/template\"");

WriteLiteral(@">

    <div class=""row"">
        <div class=""col-sm-4 ci-text"">
            <label>*Name:</label>            
        </div>        
    </div>
    
    <div class=""row"">
        <div class=""col-sm-4"">
            <input type=""text"" class=""form-control"" name=""name"" data-name=""name"" placeholder=""Enter Name Here"">
            <span class=""help-block hidden""></span>
        </div>
    </div>
    
    <div class=""row"">
        <div class=""col-sm-4 ci-text"">
            <label>*Description:</label>
        </div>
    </div>

    <div class=""row"">
        <div class=""col-sm-6"">
            <textarea class=""form-control"" name=""description"" data-name=""description"" placeholder=""Enter Desctription Here"" />
            <span class=""help-block hidden""></span>
        </div>
    </div>
    
    <div class=""well"">
        <div class=""row"">
            <div class=""col-sm-12"">
                <a href=""#"" class=""btn btn-danger js-save-condition-and-next-button"">
");

WriteLiteral("                    ");

            
            #line 33 "..\..\Areas\Customer\Views\Settings\Templates\ConditionDetailsView.cshtml"
               Write(GlobalStrings.Patient_SaveAndNextTabText);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </a>\r\n                <a href=\"#\" class=\"btn btn-primary js-sav" +
"e-condition-and-exit-button\">\r\n");

WriteLiteral("                    ");

            
            #line 36 "..\..\Areas\Customer\Views\Settings\Templates\ConditionDetailsView.cshtml"
               Write(GlobalStrings.Patient_SaveAndExitText);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </a>\r\n                <a href=\"#\" class=\"btn btn-link js-cancel" +
"-button\">\r\n");

WriteLiteral("                    ");

            
            #line 39 "..\..\Areas\Customer\Views\Settings\Templates\ConditionDetailsView.cshtml"
               Write(GlobalStrings.Edit_Customer_CancelButtonText);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </a>\r\n            </div>\r\n        </div>\r\n    </div>\r\n\r\n</scrip" +
"t>");

        }
    }
}
#pragma warning restore 1591
