#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Maestro.Common.Extensions;
    using Maestro.Web;
    using Maestro.Web.Areas.Customer;
    using Maestro.Web.Controls;
    using Maestro.Web.Resources;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Customer/Views/Settings/Templates/ProgramListItemTemplate.cshtml")]
    public partial class _Areas_Customer_Views_Settings_Templates_ProgramListItemTemplate_cshtml : Maestro.Web.BaseViewPage<dynamic>
    {
        public _Areas_Customer_Views_Settings_Templates_ProgramListItemTemplate_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" id=\"programListItemTemplate\"");

WriteLiteral(" type=\"text/template\"");

WriteLiteral(@">
    <div class=""panel panel-default"">
        <div class=""panel-heading clearfix"" role=""tab"" id=""heading-<%=id%>"">
            <input type=""hidden"" value=""<%= id %>"" name=""id"" />
            <div class=""row"">
                <div class=""col-sm-10"">
                    <h4 class=""panel-title strong"">
                        <span><%= name %></span>
                    </h4>
                </div>
                <div class=""col-sm-2 small italic text-right"">");

            
            #line 11 "..\..\Areas\Customer\Views\Settings\Templates\ProgramListItemTemplate.cshtml"
                                                         Write(GlobalStrings.ProgramList_ProgramLabel);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n            </div>\r\n        </div>\r\n        <div class=\"panel-footer clea" +
"rfix\">\r\n            <div class=\"pull-left\">\r\n                <strong>");

            
            #line 16 "..\..\Areas\Customer\Views\Settings\Templates\ProgramListItemTemplate.cshtml"
                   Write(GlobalStrings.ProgramList_DefaultLanguageLabel);

            
            #line default
            #line hidden
WriteLiteral("</strong> EN-US\r\n            </div>\r\n        </div>\r\n    </div>\r\n</script>");

        }
    }
}
#pragma warning restore 1591
