#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Maestro.Common.Extensions;
    using Maestro.Web;
    using Maestro.Web.Areas.Customer;
    using Maestro.Web.Controls;
    using Maestro.Web.Resources;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Customer/Views/Settings/Templates/UserPermissionsView.cshtml")]
    public partial class _Areas_Customer_Views_Settings_Templates_UserPermissionsView_cshtml : Maestro.Web.BaseViewPage<dynamic>
    {
        public _Areas_Customer_Views_Settings_Templates_UserPermissionsView_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" id=\"userPermissionsView\"");

WriteLiteral(" type=\"text/template\"");

WriteLiteral(">\r\n\r\n\r\n    <div id=\"permissions\">\r\n\r\n        <div class=\"actions\">\r\n            <" +
"a href=\"\" class=\"js-expand-all\">Expand All</a>|\r\n            <a href=\"\" class=\"j" +
"s-collapse-all\">Collapse All</a>\r\n        </div>\r\n\r\n        <% if (customerUserR" +
"ole) { %>\r\n        <div id=\"role-<%= customerUserRole.id %>-permissions\" class=\"" +
"role-permissions\">\r\n            <% var groups = _.groupBy(customerUserRole.permi" +
"ssions, \'category\'); %>\r\n            <% var groupsArray = _.values(groups); %>\r\n" +
"            <% _.each(groups, function (permissions, groupName, list) { %>\r\n    " +
"        <% var index =  _.indexOf(groupsArray, permissions)%>\r\n            <div " +
"class=\"permission-group accordion list-accordion\">\r\n                <div class=\"" +
"permission-group-heading accordion-heading row\">\r\n                    <div class" +
"=\"col-xs-12\">\r\n                        <a class=\"accordion-toggle collapsed list" +
"-collapse active-list\"\r\n                           role=\"button\" data-toggle=\"co" +
"llapse\" href=\"#permission-group-content-<%= index %>\">\r\n                        " +
"    <div class=\"list-arrow\"></div>\r\n                            <%= groupName %>" +
"\r\n                        </a>\r\n                    </div>\r\n                </di" +
"v>\r\n                <div id=\"permission-group-content-<%= index %>\" class=\"permi" +
"ssion-group-content accordion-content accordion-body collapse\">\r\n               " +
"     <% _.each(permissions, function (permission) { %>\r\n                    <div" +
" class=\"row\">\r\n                        <div class=\"col-xs-6\">\r\n                 " +
"           <p><%= permission.name %></p>\r\n                            <p class=\"" +
"small\"><%= permission.description %></p>\r\n                        </div>\r\n      " +
"                  <div class=\"col-xs-6\">Permission controls</div>\r\n             " +
"       </div>\r\n                    <% }); %>\r\n                </div>\r\n          " +
"  </div>\r\n            <% }); %>\r\n        </div>\r\n        <% } %>\r\n    </div>\r\n\r\n" +
"\r\n</script>");

        }
    }
}
#pragma warning restore 1591
