#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Maestro.Web;
    using Maestro.Web.Controls;
    
    #line 1 "..\..\Views\Account\ChangePassword.cshtml"
    using Maestro.Web.Models.Users;
    
    #line default
    #line hidden
    using Maestro.Web.Resources;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/ChangePassword.cshtml")]
    public partial class _Views_Account_ChangePassword_cshtml : Maestro.Web.BaseViewPage<Maestro.Web.Models.Users.ChangePasswordViewModel>
    {
        public _Views_Account_ChangePassword_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Account\ChangePassword.cshtml"
  
    Layout = "~/Views/Shared/_PublicLayout.cshtml";
    ViewBag.Title = GlobalStrings.Users_ChangePassword_PageTitle;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n        <h1");

WriteLiteral(" class=\"page-header-ci\"");

WriteLiteral(">");

            
            #line 10 "..\..\Views\Account\ChangePassword.cshtml"
                              Write(GlobalStrings.Users_ChangePassword_PageTitle);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-6 bg-warning warning-message\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 14 "..\..\Views\Account\ChangePassword.cshtml"
           Write(GlobalStrings.Users_ChangePassword_NotificationMessage);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"ci-content\"");

WriteLiteral(">\r\n");

            
            #line 19 "..\..\Views\Account\ChangePassword.cshtml"
            
            
            #line default
            #line hidden
            
            #line 19 "..\..\Views\Account\ChangePassword.cshtml"
             using (Html.BeginForm("ChangePassword", "Account", null, FormMethod.Post, new { @class = "ci-change-pwd-form" }))
            {

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-xs-2 ci-text\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 23 "..\..\Views\Account\ChangePassword.cshtml"
                   Write(Html.LabelFor(model => model.Email, new { @class = "strong" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"col-xs-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 26 "..\..\Views\Account\ChangePassword.cshtml"
                   Write(Html.TextBoxFor(model => model.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"input-sub-note x-small error-state\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 28 "..\..\Views\Account\ChangePassword.cshtml"
                       Write(Html.ValidationMessageFor(model => model.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                </d" +
"iv>\r\n");

            
            #line 32 "..\..\Views\Account\ChangePassword.cshtml"


            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-xs-2 ci-text\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 35 "..\..\Views\Account\ChangePassword.cshtml"
                   Write(Html.LabelFor(model => model.CurrentPassword, new {@class = "strong"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"col-xs-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 38 "..\..\Views\Account\ChangePassword.cshtml"
                   Write(Html.PasswordFor(model => model.CurrentPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                        <div");

WriteLiteral(" class=\"input-sub-note x-small error-state\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 41 "..\..\Views\Account\ChangePassword.cshtml"
                       Write(Html.ValidationMessageFor(model => model.CurrentPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n\r\n                        <div");

WriteLiteral(" class=\"x-small error-state\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 45 "..\..\Views\Account\ChangePassword.cshtml"
                       Write(Html.ValidationMessage(ChangePasswordViewModel.IncorrectCredentialsKey));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                </d" +
"iv>\r\n");

            
            #line 49 "..\..\Views\Account\ChangePassword.cshtml"


            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-xs-2 ci-text\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 52 "..\..\Views\Account\ChangePassword.cshtml"
                   Write(Html.LabelFor(model => model.NewPassword, new {@class = "strong"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"col-xs-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 55 "..\..\Views\Account\ChangePassword.cshtml"
                   Write(Html.PasswordFor(model => model.NewPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                        <div");

WriteLiteral(" class=\"input-sub-note x-small error-state\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 58 "..\..\Views\Account\ChangePassword.cshtml"
                       Write(Html.ValidationMessageFor(model => model.NewPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                </d" +
"iv>\r\n");

            
            #line 62 "..\..\Views\Account\ChangePassword.cshtml"


            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-xs-2 ci-text\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 65 "..\..\Views\Account\ChangePassword.cshtml"
                   Write(Html.LabelFor(model => model.ConfirmNewPassword, new { @class = "strong" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"col-xs-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 68 "..\..\Views\Account\ChangePassword.cshtml"
                   Write(Html.PasswordFor(model => model.ConfirmNewPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                        <div");

WriteLiteral(" class=\"input-sub-note x-small error-state\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 71 "..\..\Views\Account\ChangePassword.cshtml"
                       Write(Html.ValidationMessageFor(model => model.ConfirmNewPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                </d" +
"iv>\r\n");

            
            #line 75 "..\..\Views\Account\ChangePassword.cshtml"


            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-xs-6 text-right\"");

WriteLiteral(">\r\n                        <button");

WriteLiteral(" id=\"btn-sign-in\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(">");

            
            #line 78 "..\..\Views\Account\ChangePassword.cshtml"
                                                                                  Write(GlobalStrings.Users_ChangePassword_ChangePasswordButtonTitle);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                    </div>\r\n                </div>\r\n");

            
            #line 81 "..\..\Views\Account\ChangePassword.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n    </div>\r\n</div>\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 88 "..\..\Views\Account\ChangePassword.cshtml"
Write(Scripts.Render("~/bundles/js/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
