#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Maestro.Web;
    using Maestro.Web.Controls;
    
    #line 1 "..\..\Views\Account\Login.cshtml"
    using Maestro.Web.Models.Users;
    
    #line default
    #line hidden
    using Maestro.Web.Resources;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/Login.cshtml")]
    public partial class _Views_Account_Login_cshtml : Maestro.Web.BaseViewPage<LoginViewModel>
    {
        public _Views_Account_Login_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 4 "..\..\Views\Account\Login.cshtml"
  
    Layout = "~/Views/Shared/_PublicLayout.cshtml";
    ViewBag.Title = GlobalStrings.Users_Login_PageTitle;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n        \r\n        <!-- MAIN CONTENT - SITE ADMIN -->\r\n        <div");

WriteLiteral(" class=\"ci-content\"");

WriteLiteral(">\r\n");

            
            #line 14 "..\..\Views\Account\Login.cshtml"
            
            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\Account\Login.cshtml"
             using (Html.BeginForm("Login", "Account", new {returnUrl = Model.ReturnUrl}, FormMethod.Post, new {@class = "form-signin-ci"}))
            {

            
            #line default
            #line hidden
WriteLiteral("                <h2");

WriteLiteral(" class=\"form-signin-heading-ci\"");

WriteLiteral(">");

            
            #line 16 "..\..\Views\Account\Login.cshtml"
                                              Write(GlobalStrings.Users_Login_PageTitle);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n");

            
            #line 17 "..\..\Views\Account\Login.cshtml"

                
            
            #line default
            #line hidden
            
            #line 18 "..\..\Views\Account\Login.cshtml"
           Write(Html.LabelFor(model => model.Email, new {@class = "sr-only"}));

            
            #line default
            #line hidden
            
            #line 18 "..\..\Views\Account\Login.cshtml"
                                                                              
                
            
            #line default
            #line hidden
            
            #line 19 "..\..\Views\Account\Login.cshtml"
           Write(Html.TextBoxFor(model => model.Email, new {@type = "email", @autofocus = "autofocus", @required = "required", @placeholder = "Email address", @class = "form-control" }));

            
            #line default
            #line hidden
            
            #line 19 "..\..\Views\Account\Login.cshtml"
                                                                                                                                                                                         

                
            
            #line default
            #line hidden
            
            #line 21 "..\..\Views\Account\Login.cshtml"
           Write(Html.LabelFor(model => model.Password, new {@class = "sr-only"}));

            
            #line default
            #line hidden
            
            #line 21 "..\..\Views\Account\Login.cshtml"
                                                                                 
                
            
            #line default
            #line hidden
            
            #line 22 "..\..\Views\Account\Login.cshtml"
           Write(Html.PasswordFor(model => model.Password, new {@required = "required", @placeholder = "Password", @class = "form-control" }));

            
            #line default
            #line hidden
            
            #line 22 "..\..\Views\Account\Login.cshtml"
                                                                                                                                             


            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"validation-message-ci\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 25 "..\..\Views\Account\Login.cshtml"
               Write(Html.ValidationMessage(LoginViewModel.IncorrectCredentialsKey));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 26 "..\..\Views\Account\Login.cshtml"
               Write(Html.ValidationMessageFor(model => model.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 27 "..\..\Views\Account\Login.cshtml"
               Write(Html.ValidationMessageFor(model => model.Password));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n");

            
            #line 29 "..\..\Views\Account\Login.cshtml"


            
            #line default
            #line hidden
WriteLiteral("                <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-lg btn-primary btn-block\"");

WriteLiteral(">");

            
            #line 30 "..\..\Views\Account\Login.cshtml"
                                                                          Write(GlobalStrings.Users_Login_LoginButtonTitle);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n");

            
            #line 31 "..\..\Views\Account\Login.cshtml"

            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n\r\n        <!-- END MAIN CONTENT -->\r\n    </div>\r\n</div>\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 41 "..\..\Views\Account\Login.cshtml"
Write(Scripts.Render("~/bundles/js/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 42 "..\..\Views\Account\Login.cshtml"
Write(Scripts.Render("~/bundles/js/login"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
