// <auto-generated />
namespace VitalsService.DataAccess.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_conditions_and_tags : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_conditions_and_tags));
        
        string IMigrationMetadata.Id
        {
            get { return "201604271054263_Add_conditions_and_tags"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
