#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Maestro.Web;
    using Maestro.Web.Areas.Site;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Site/Views/Patients/Templates/PatientDetails/Dashboard/PatientDashboardPe" +
        "ripheralsViewTemplate.cshtml")]
    public partial class _Areas_Site_Views_Patients_Templates_PatientDetails_Dashboard_PatientDashboardPeripheralsViewTemplate_cshtml : Maestro.Web.BaseViewPage<dynamic>
    {
        public _Areas_Site_Views_Patients_Templates_PatientDetails_Dashboard_PatientDashboardPeripheralsViewTemplate_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" id=\"patientDashboardPeripheralsViewTemplate\"");

WriteLiteral(" type=\"text/template\"");

WriteLiteral(@">
    <nav class=""navbar navbar-default"">
        <div class=""navbar-title-ci"">Peripherals</div>
    </nav>

    <div class=""aside-block-content"">
        <% if (isModelFetched) { %>
            <ul class=""devices-list"">
                <% _.each(devices, function (device) { %>
                    <li>
                        <span><%= _.values(device)[0] %></span>
                    </li>
                <% }); %>
            </ul>
        <% } else { %>
            <img src=""/Content/img/spinner.gif"" class=""spinner"" />
        <% } %>
        <a class=""btn btn-primary btn-lg js-manage-peripherals"" href=""/<%=siteId%>/Patients/EditPatient/<%=id%>/Measurements/"">Manage Peripherals</a>
    </div>
</script>");

        }
    }
}
#pragma warning restore 1591
