#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Maestro.Web;
    using Maestro.Web.Areas.Site;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Site/Views/Patients/Templates/PatientDetails/Dashboard/PatientDashboardHe" +
        "althSessionsViewTemplate.cshtml")]
    public partial class _Areas_Site_Views_Patients_Templates_PatientDetails_Dashboard_PatientDashboardHealthSessionsViewTemplate_cshtml : Maestro.Web.BaseViewPage<dynamic>
    {
        public _Areas_Site_Views_Patients_Templates_PatientDetails_Dashboard_PatientDashboardHealthSessionsViewTemplate_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" id=\"patientDashboardHealthSessionsViewTemplate\"");

WriteLiteral(" type=\"text/template\"");

WriteLiteral(">\r\n    <nav class=\"navbar navbar-default\">\r\n        <div class=\"navbar-title-ci\">" +
"Health Sessions</div>\r\n    </nav>\r\n\r\n    <div class=\"aside-block-content\">\r\n    " +
"    <div class=\"missed-health-sessions <%= healthSessionsMissedCount ? \'warning\'" +
" : \'\'%>\">\r\n            <% if (isModelFetched) { %>\r\n                <% if (healt" +
"hSessionsMissedCount) { %>\r\n                    <p><%= healthSessionsMissedCount" +
" %> Sessions Missed</p>\r\n                <% } else { %>\r\n                    <p>" +
"No missed sessions</p>\r\n                <% } %>\r\n            <% } %>\r\n          " +
"  <a class=\"btn btn-primary btn-lg js-check-connection\">Check Connection</a>\r\n  " +
"      </div>\r\n\r\n        <table class=\"table table-striped health-sessions-data-l" +
"ist\">\r\n            <% if (isModelFetched) { %>\r\n                <tr>\r\n          " +
"          <td>\r\n                        <label>Next Session:</label>\r\n          " +
"              <% if (nextSessionText) { %>\r\n                            <span><%" +
"= nextSessionText %></span>\r\n                        <% } else { %>\r\n           " +
"                 <span>&mdash;</span>\r\n                        <% } %>\r\n        " +
"            </td>\r\n                </tr>\r\n                <tr>\r\n                " +
"    <td>\r\n                        <label>Programs:</label>\r\n                    " +
"    <% if (currentPrograms.length) { %>\r\n                            <ul class=\"" +
"list-unstyled\">\r\n                                <% _.each(currentPrograms, func" +
"tion (programName) { %>\r\n                                <li><%= programName %><" +
"/li>\r\n                                <% }) %>\r\n                            </ul" +
">\r\n                        <% } else { %>\r\n                            <span>&md" +
"ash;</span>\r\n                        <% } %>\r\n                    </td>\r\n       " +
"         </tr>\r\n                <tr>\r\n                    <td>\r\n                " +
"        <label>Current Time for Patient:</label><span><%= currentTimeForPatient " +
"%></span>\r\n                    </td>\r\n                </tr>\r\n                <tr" +
">\r\n                    <td>\r\n                        <label>Preferred Session Ti" +
"me:</label><span><%= preferredSessionTime %></span>\r\n                    </td>\r\n" +
"                </tr>\r\n                <tr>\r\n                    <td>\r\n         " +
"               <label>Last Connected <%= lastConnectedDeviceType ? \'(\'+lastConne" +
"ctedDeviceType+\')\' : \'\'%>:</label><span><%= lastConnectedDateText ? lastConnecte" +
"dDateText : \'unknown\' %></span>\r\n                    </td>\r\n                </tr" +
">\r\n            <% } else { %>\r\n                <img src=\"/Content/img/spinner.gi" +
"f\" class=\"spinner\" />\r\n            <% } %>\r\n        </table>\r\n\r\n        <a class" +
"=\"btn btn-primary btn-lg\" href=\"/<%=siteId%>/Patients/PatientDetails/<%=id%>/Sch" +
"edule/\">Schedule a Program</a>\r\n    </div>\r\n</script>");

        }
    }
}
#pragma warning restore 1591
