#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Maestro.Web;
    using Maestro.Web.Areas.Site;
    
    #line 1 "..\..\Areas\Site\Views\Patients\Templates\_PatientEditCareManagersTemplate.cshtml"
    using Maestro.Web.Resources;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Site/Views/Patients/Templates/_PatientEditCareManagersTemplate.cshtml")]
    public partial class _Areas_Site_Views_Patients_Templates__PatientEditCareManagersTemplate_cshtml : Maestro.Web.BaseViewPage<dynamic>
    {
        public _Areas_Site_Views_Patients_Templates__PatientEditCareManagersTemplate_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<h3>Assign Care Managers</h3>\r\n\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral("><a");

WriteLiteral(" class=\"js-assign-all-care-manager\"");

WriteLiteral(">Assign All</a></div>\r\n    <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral("><a");

WriteLiteral(" class=\"js-remove-all-care-manager\"");

WriteLiteral(">Remove All</a></div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(" id=\"available-care-managers-container\"");

WriteLiteral("></div>\r\n    <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(" id=\"assigned-care-managers-container\"");

WriteLiteral("></div>\r\n</div>\r\n\r\n<div");

WriteLiteral(" class=\"well\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" href=\"EditPatient/<%=id%>/Measurements/\"");

WriteLiteral(" class=\"btn btn-danger js-patient-care-managers-save\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 18 "..\..\Areas\Site\Views\Patients\Templates\_PatientEditCareManagersTemplate.cshtml"
           Write(GlobalStrings.Patient_SaveAndNextTabText);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </a>\r\n            <a");

WriteLiteral(" href=\"PatientDetails/<%=id%>/\"");

WriteLiteral(" class=\"btn btn-primary js-patient-care-managers-save\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 21 "..\..\Areas\Site\Views\Patients\Templates\_PatientEditCareManagersTemplate.cshtml"
           Write(GlobalStrings.Patient_SaveAndExitText);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </a>\r\n            <a");

WriteLiteral(" href=\"PatientDetails/<%=id%>/\"");

WriteLiteral(" class=\"btn btn-link js-patient-care-managers-cancel\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 24 "..\..\Areas\Site\Views\Patients\Templates\_PatientEditCareManagersTemplate.cshtml"
           Write(GlobalStrings.Edit_Customer_CancelButtonText);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </a>\r\n        </div>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
