#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Maestro.Web;
    using Maestro.Web.Areas.Site;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Site/Views/Patients/Templates/PatientCalendarProgramModalTemplate.cshtml")]
    public partial class _Areas_Site_Views_Patients_Templates_PatientCalendarProgramModalTemplate_cshtml : Maestro.Web.BaseViewPage<dynamic>
    {
        public _Areas_Site_Views_Patients_Templates_PatientCalendarProgramModalTemplate_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" id=\"patientCalendarProgramModalTemplate\"");

WriteLiteral(" type=\"text/template\"");

WriteLiteral(">\r\n    <div class=\"alert alert-danger hidden\" role=\"alert\"></div>\r\n    <h4>Care E" +
"lement</h4>\r\n    <div class=\"row form-horizontal\">\r\n        <div class=\"col-sm-7" +
"\">\r\n            <div class=\"form-group\">\r\n                <label for=\"startDate\"" +
" class=\"col-sm-6 control-label\">Start Date</label>\r\n                <div class=\"" +
"col-sm-6\">\r\n                    <div id=\"startDate-datetimepicker\" class=\"input-" +
"group\">\r\n                        <input type=\"text\" class=\"form-control\" id=\"sta" +
"rtDateDp\" name=\"startDateDp\">\r\n                        <span class=\"input-group-" +
"addon\">\r\n                            <span class=\"glyphicon glyphicon-calendar\">" +
"</span>\r\n                        </span>\r\n                    </div>\r\n          " +
"          <input type=\"hidden\" id=\"startDate\" name=\"startDate\">\r\n               " +
"     <span class=\"help-block help-block-error help-block-startDate hidden\"></spa" +
"n>\r\n                </div>\r\n            </div>\r\n            <div class=\"form-gro" +
"up\">\r\n                <label for=\"estimatedEndDate\" class=\"col-sm-6 control-labe" +
"l\">Estimated End Date</label>\r\n                <div class=\"col-sm-6\">\r\n         " +
"           <input type=\"text\" name=\"estimatedEndDate\" class=\"form-control\" id=\"e" +
"stimatedEndDate\" readonly=\"readonly\">\r\n                </div>\r\n            </div" +
">\r\n        </div>\r\n        <div class=\"col-sm-5\">\r\n            <div class=\"form-" +
"group\">\r\n                <label for=\"startDay\" class=\"col-sm-7 offset-right-0 co" +
"ntrol-label\">Start Program Day</label>\r\n                <div class=\"col-sm-5\">\r\n" +
"                    <input type=\"number\" class=\"form-control\" id=\"startDay\" name" +
"=\"startDay\" data-name=\"startDay\">\r\n                </div>\r\n                <span" +
" class=\"col-sm-12 help-block help-block-error help-block-startDay hidden\"></span" +
">\r\n            </div>\r\n            <div class=\"form-group\">\r\n                <la" +
"bel for=\"endDay\" class=\"col-sm-7 offset-right-0 control-label\">End Program Day</" +
"label>\r\n                <div class=\"col-sm-5\">\r\n                    <input type=" +
"\"number\" class=\"form-control\" id=\"endDay\" name=\"endDay\" data-name=\"endDay\">\r\n   " +
"             </div>\r\n                <span class=\"col-sm-12 help-block help-bloc" +
"k-error help-block-endDay hidden\"></span>\r\n            </div>\r\n        </div>\r\n " +
"   </div>\r\n    <h4>Program Time</h4>\r\n    <div class=\"row form-horizontal\">\r\n   " +
"     <div class=\"col-sm-7\">\r\n            <div class=\"radio\">\r\n                <l" +
"abel style=\"white-space: nowrap\">\r\n                    <input type=\"radio\" name=" +
"\"timeType\" id=\"defaultTime\" value=\"defaultTime\">\r\n                    Default to" +
" patient preferred time (<%- obj.preferredSessionTime %>)\r\n                </lab" +
"el>\r\n            </div>\r\n            <div class=\"radio\">\r\n                <label" +
">\r\n                    <input type=\"radio\" name=\"timeType\" id=\"differentTime\" va" +
"lue=\"differentTime\">\r\n                    Select a different time\r\n             " +
"   </label>\r\n            </div>\r\n            <div class=\"form-group col-sm-6\">\r\n" +
"                <div class=\"input-group program-time-ci\" id=\"programTime-time\">\r" +
"\n                    <input type=\"text\" class=\"form-control\" id=\"programTimeTp\" " +
"name=\"programTimeTp\" value=\"\">\r\n                    <span class=\"input-group-add" +
"on\">\r\n                        <span class=\"glyphicon glyphicon-time\"></span>\r\n  " +
"                  </span>\r\n                </div>\r\n                <input type=\"" +
"hidden\" id=\"programTime\" name=\"programTime\" data-name=\"programTime\" value=\"\">\r\n " +
"           </div>\r\n        </div>\r\n        <div class=\"col-sm-5\">\r\n            <" +
"div class=\"form-group\">\r\n                <label for=\"validHours\" class=\"col-sm-4" +
" offset-right-0 control-label\">Valid for</label>\r\n                <div class=\"co" +
"l-sm-8\">\r\n                    <div class=\"input-group\">\r\n                       " +
" <input type=\"number\" class=\"form-control\" id=\"validHours\" name=\"validHours\" dat" +
"a-name=\"validHours\">\r\n                        <span class=\"input-group-addon\">Ho" +
"urs</span>\r\n                    </div>\r\n                    <span class=\"help-bl" +
"ock help-block-error help-block-validHours hidden\"></span>\r\n                </di" +
"v>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</script>");

        }
    }
}
#pragma warning restore 1591
