#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Maestro.Web;
    using Maestro.Web.Areas.Site;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Site/Views/Patients/Templates/PatientTrendsVitalReadingFlyoutTemplate.csh" +
        "tml")]
    public partial class _Areas_Site_Views_Patients_Templates_PatientTrendsVitalReadingFlyoutTemplate_cshtml : Maestro.Web.BaseViewPage<dynamic>
    {
        public _Areas_Site_Views_Patients_Templates_PatientTrendsVitalReadingFlyoutTemplate_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" id=\"patientTrendsVitalReadingFlyoutTemplate\"");

WriteLiteral(" type=\"text/template\"");

WriteLiteral(">\r\n    <span class=\"chart-flyout vital-reading-flyout\">\r\n        <span class=\"hea" +
"der\">\r\n            <span><%= headerText %></span>\r\n            <a href=\"\" class=" +
"\"close js-close-tooltip\"><i class=\"fa fa-times-circle\"></i></a>\r\n        </span>" +
"\r\n        <% if (readingsNumber > 1) { %>\r\n            <span class=\"text-block\">" +
"<label>Avg Reading:</label> <%= avgText %></span>\r\n            <span class=\"text" +
"-block\"><label>No. of Readings:</label> <%= readingsNumber %></span>\r\n          " +
"  <% if (readingsNumber > 5) { %>\r\n                <span class=\"text-block\"><a h" +
"ref=\"\">View all readings</a></span>\r\n            <% } %>\r\n            <span clas" +
"s=\"text-block\">\r\n                <ul class=\"readings\">\r\n                    <% _" +
".each(readingItems, function (reading) { %>\r\n\r\n                    <li style=\"co" +
"lor: <%= reading.textColor %>\">\r\n                        <% if (!reading.isAutom" +
"ated) { %>\r\n                            <sup class=\"is-manual\"><span class=\"fa f" +
"a-asterisk\"></span></sup>\r\n                        <% } %>\r\n                    " +
"    <span><%= reading.date %></span>\r\n                        <span><%= reading." +
"time %></span>\r\n                        <span><%= reading.value %></span>\r\n     " +
"               </li>\r\n\r\n                    <% }); %>\r\n                </ul>\r\n  " +
"          </span>\r\n        <% } else { %>\r\n            <span class=\"text-block\">" +
"\r\n                <label>Reading:</label>\r\n                <span style=\"color: <" +
"%= avgTextColor %>\"><%= avgText %></span>\r\n            </span>\r\n        <% } %>\r" +
"\n    </span>\r\n</script>");

        }
    }
}
#pragma warning restore 1591
