#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Maestro.Web;
    using Maestro.Web.Areas.Site;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Site/Views/Patients/Templates/PatientHealthSessionContainerTemplate.cshtm" +
        "l")]
    public partial class _Areas_Site_Views_Patients_Templates_PatientHealthSessionContainerTemplate_cshtml : Maestro.Web.BaseViewPage<dynamic>
    {
        public _Areas_Site_Views_Patients_Templates_PatientHealthSessionContainerTemplate_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" id=\"patientHealthSessionContainerTemplate\"");

WriteLiteral(" type=\"text/template\"");

WriteLiteral(">\r\n\r\n    <ul class=\"nav nav-pills nav-pills-sm-ci nav-pills-session-ci\" role=\"tab" +
"list\">\r\n        <li role=\"presentation\" class=\"active\">\r\n            <a href=\"#t" +
"ab-session-creation\" role=\"tab\" data-toggle=\"tab\">\r\n                Add Content\r" +
"\n            </a>\r\n        </li>\r\n        <li role=\"presentation\">\r\n            " +
"<a href=\"#tab-session-schedule\" role=\"tab\" data-toggle=\"tab\">\r\n                S" +
"chedule\r\n                <span id=\"session-protocol-count\" class=\"hidden\"></span" +
">\r\n            </a>\r\n        </li>\r\n    </ul>\r\n    <div class=\"new-session-label" +
"\">New Session</div>\r\n    <div class=\"tab-content\">\r\n        <div role=\"tabpanel\"" +
" class=\"tab-pane active\" id=\"tab-session-creation\">\r\n            <div class=\"for" +
"m-search-small-ci\">\r\n                <div class=\"form-group\">\r\n                 " +
"   <input class=\"form-control\" type=\"text\" id=\"search-protocol-elements-keyword\"" +
" placeholder=\"Type Keyword here\">\r\n                </div>\r\n                <div " +
"class=\"form-group\">\r\n                    <div class=\"input-group\">\r\n            " +
"            <select id=\"search-protocol-elements-tags\" data-placeholder=\"Search " +
"by Tags\" data-loading-placeholder=\"Loading...\" class=\"form-control chosen-select" +
" searching-tags\"></select>\r\n                        <span class=\"input-group-btn" +
" js-search-protocol-clear-container\">\r\n                            <button class" +
"=\"btn btn-default js-search-protocol-clear\" type=\"button\">\r\n                    " +
"            <span class=\"glyphicon glyphicon-remove\"></span>\r\n                  " +
"          </button>\r\n                        </span>\r\n                    </div>" +
"\r\n                </div>\r\n            </div>\r\n            <hr />\r\n            <d" +
"iv id=\"patient-protocol-search-result\" class=\"b-patient-session-protocols protoc" +
"ols-search\"></div>\r\n        </div>\r\n        <div role=\"tabpanel\" class=\"tab-pane" +
"\" id=\"tab-session-schedule\">\r\n            <div class=\"b-patient-session-protocol" +
"s\">\r\n                <div class=\"form-group\">\r\n                    <input type=\"" +
"text\" class=\"form-control\" name=\"name\" data-name=\"name\" placeholder=\"New Session" +
"\">\r\n                    <span class=\"help-block hidden\"></span>\r\n               " +
" </div>\r\n                <hr />\r\n                <div id=\"session-protocol-colle" +
"ction\" class=\"session-protocol-collection-ci\"></div>\r\n                <hr />\r\n  " +
"              <div class=\"form-horizontal hide-grid-ci\">\r\n                    <%" +
" if( !isEdit ){%>\r\n                        <div class=\"form-group\">\r\n           " +
"                 <div class=\"col-sm-12 checkbox\">\r\n                             " +
"   <label>\r\n                                    <input type=\"checkbox\" name=\"isD" +
"efault\" id=\"isDefault\"> Make this the Default Health Session\r\n                  " +
"              </label>\r\n                            </div>\r\n                    " +
"    </div>\r\n                    <% } %>\r\n                    <% if( isEdit && is" +
"Default ) {%>\r\n                        <div class=\"default-health-session-edit-l" +
"abel-ci\">\r\n                            There are no schedule details to<br>\r\n   " +
"                         show. This is the Health Session that<br>\r\n            " +
"                is always available to the Patient and<br>\r\n                    " +
"        that can be taken an unlimited<br>\r\n                            number o" +
"f times.\r\n                        </div>\r\n                    <% } %>\r\n\r\n       " +
"             <% if( ( isEdit && !isDefault ) || !isEdit ) {%>\r\n                 " +
"       <div id=\"regular-health-session-fields\">\r\n                            <h5" +
">Session Duration</h5>\r\n                            <div class=\"form-group\">\r\n  " +
"                              <label for=\"startDate\" class=\"col-sm-5 control-lab" +
"el offset-right-0\">Start Date</label>\r\n                                <div clas" +
"s=\"col-sm-7\">\r\n                                    <div id=\"startDate-datetimepi" +
"cker\" class=\"input-group\">\r\n                                        <input type=" +
"\"text\" class=\"form-control\" id=\"startDateDp\" name=\"startDateDp\">\r\n              " +
"                          <span class=\"input-group-addon\">\r\n                    " +
"                        <span class=\"glyphicon glyphicon-calendar\"></span>\r\n    " +
"                                    </span>\r\n                                   " +
" </div>\r\n                                    <input type=\"hidden\" id=\"startDate\"" +
" name=\"startDate\" data-name=\"startDate\">\r\n                                    <s" +
"pan class=\"help-block help-block-error help-block-startDate hidden\"></span>\r\n   " +
"                             </div>\r\n                            </div>\r\n       " +
"                     <h5>Session Time</h5>\r\n                            <div cla" +
"ss=\"form-group\">\r\n                                <div class=\"col-sm-12\">     \r\n" +
"                                    <div class=\"radio\">\r\n                       " +
"                 <label>\r\n                                            <input typ" +
"e=\"radio\" name=\"timeType\" id=\"defaultTime\" value=\"defaultTime\">\r\n               " +
"                             Default to patient preferred time (<%=preferredSess" +
"ionTime%>)\r\n                                        </label>\r\n                  " +
"                  </div>\r\n                                </div>\r\n              " +
"              </div>\r\n                            <div class=\"form-group\">\r\n    " +
"                            <div class=\"col-sm-12 offset-right-0\">\r\n            " +
"                        <div class=\"radio\">\r\n                                   " +
"     <label>\r\n                                            <input type=\"radio\" na" +
"me=\"timeType\" id=\"differentTime\" value=\"differentTime\">\r\n                       " +
"                     Select a different time\r\n                                  " +
"      </label>\r\n                                    </div>\r\n                    " +
"            </div>\r\n                            </div>\r\n                        " +
"    <div class=\"form-group\">\r\n                                <div class=\"col-sm" +
"-5\"></div>\r\n                                <div class=\"col-sm-7\">\r\n            " +
"                        <div class=\"input-group\" id=\"sessionTime-time\">\r\n       " +
"                                 <input type=\"text\" class=\"form-control\" id=\"ses" +
"sionTimeTp\" name=\"sessionTimeTp\" data-name=\"sessionTime\" value=\"\">\r\n            " +
"                            <span class=\"input-group-addon\">\r\n                  " +
"                          <span class=\"glyphicon glyphicon-time\"></span>\r\n      " +
"                                  </span>\r\n                                    <" +
"/div>\r\n                                    <input type=\"hidden\" id=\"sessionTime\"" +
" name=\"sessionTime\" data-name=\"sessionTime\">\r\n                                  " +
"  <span class=\"help-block help-block-error help-block-sessionTime hidden\"></span" +
">\r\n                                </div>\r\n                            </div>\r\n\r" +
"\n                            <div class=\"form-group overlay-container\">\r\n       " +
"                         <label for=\"expireMinutes\" class=\"col-sm-5 control-labe" +
"l offset-right-0\">Valid For</label>\r\n                                <div class=" +
"\"col-sm-4\">\r\n                                    <input type=\"text\" class=\"form-" +
"control\" id=\"expireHours\" name=\"expireHours\" data-name=\"expireHours\" value=\"\">\r\n" +
"                                    <input type=\"hidden\" id=\"expireMinutes\" name" +
"=\"expireMinutes\" >\r\n                                    <span class=\"help-block " +
"help-block-error help-block-expireHours hidden\"></span>\r\n                       " +
"         </div>\r\n                                <label for=\"expireMinutes\" clas" +
"s=\"col-sm-3 control-label text-left offset-left-0\">Hours</label>\r\n              " +
"                  <span class=\"overlay js-valid-for-overlay\" style=\"display: non" +
"e;\"></span>\r\n                            </div>\r\n                            <di" +
"v class=\"form-group\">\r\n                                <div class=\"col-sm-12 che" +
"ckbox\">\r\n                                    <label>\r\n                          " +
"              <input type=\"checkbox\" name=\"isNeverExpiring\" id=\"isNeverExpiring\"" +
"> Never Expires\r\n                                    </label>\r\n                 " +
"               </div>\r\n\r\n                                <div class=\"col-sm-12 c" +
"heckbox\">\r\n                                    <label>\r\n                        " +
"                <input type=\"checkbox\" name=\"isRecurring\" id=\"isRecurring\"> Make" +
" this a Recurring Session\r\n                                    </label>\r\n       " +
"                         </div>\r\n                            </div>\r\n           " +
"                 <div id=\"recurring-session-rules\" class=\"hidden\"></div>\r\n      " +
"                  </div>\r\n                    <% } %>\r\n                </div>\r\n " +
"               <p class=\"help-block help-block-error help-block-session-occurren" +
"ces hidden\"></p>\r\n                <div class=\"session-protocols-submit\">\r\n      " +
"              <button class=\"btn btn-link js-cancel-session\">Cancel</button>\r\n  " +
"                  <% if( isEdit ){%>\r\n                    <button class=\"btn btn" +
"-primary js-create-session disabled\">Update</button>\r\n                    <%}els" +
"e{%>\r\n                    <button class=\"btn btn-primary js-create-session disab" +
"led\">Create</button>\r\n                    <%}%>\r\n                </div>\r\n       " +
"     </div>\r\n        </div>\r\n    </div>\r\n</script>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
