#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Maestro.Web;
    using Maestro.Web.Areas.Site;
    
    #line 1 "..\..\Areas\Site\Views\Patients\Templates\PatientSearchBoxTemplate.cshtml"
    using Maestro.Web.Resources;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Site/Views/Patients/Templates/PatientSearchBoxTemplate.cshtml")]
    public partial class _Areas_Site_Views_Patients_Templates_PatientSearchBoxTemplate_cshtml : Maestro.Web.BaseViewPage<dynamic>
    {
        public _Areas_Site_Views_Patients_Templates_PatientSearchBoxTemplate_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" id=\"PatientSearchBoxTemplate\"");

WriteLiteral(" type=\"text/template\"");

WriteLiteral(">\r\n    <div class=\"row form-group\">\r\n        <div class=\"col-sm-2\">\r\n            " +
"<a class=\"btn btn-primary form-control js-patient-add\" href=\"CreatePatient/\">");

            
            #line 7 "..\..\Areas\Site\Views\Patients\Templates\PatientSearchBoxTemplate.cshtml"
                                                                                    Write(GlobalStrings.Patients_AddPatientText);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n        </div>\r\n        <div class=\"col-sm-5\">\r\n            <div class=\"inp" +
"ut-group typeahead-wrapper\">\r\n                <input type=\"text\" class=\"form-con" +
"trol typeahead\" />\r\n                <div class=\"typeahead-actions\">\r\n           " +
"         <span class=\"glyphicon glyphicon-refresh\"></span>\r\n                    " +
"<span class=\"glyphicon glyphicon-remove\"></span>\r\n                </div>\r\n      " +
"          <span class=\"input-group-btn\">\r\n                    <button id=\"sugges" +
"tion-box-search\" class=\"btn btn-default\" type=\"button\">\r\n                       " +
" <span class=\"glyphicon glyphicon-search\"></span>\r\n                    </button>" +
"\r\n                    <% if(obj.hasIdentifiers) { %>\r\n                    <a id=" +
"\"advanced-search-button\" class=\"btn btn-default\" data-toggle=\"collapse\" aria-exp" +
"anded=\"false\" aria-controls=\"collapseAdvancedSearch\" href=\"#collapseAdvancedSear" +
"ch\">\r\n                        <span class=\"glyphicon glyphicon-list\"></span>\r\n  " +
"                  </a>\r\n                    <% } %>\r\n                </span>\r\n  " +
"          </div>\r\n        </div>\r\n        <div class=\"col-sm-5\">\r\n            <d" +
"iv class=\"checkbox checkbox-ci\">\r\n                <label>\r\n                    <" +
"input type=\"checkbox\" id=\"suggestion-box-inactive\">Show inactive patients\r\n     " +
"           </label>\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <% if(o" +
"bj.managePermission) { %>\r\n    <div class=\"row\">\r\n        <div class=\"col-sm-12 " +
"form-horizontal\">\r\n            <div class=\"form-group\">\r\n                <label " +
"for=\"suggestion-box-manage-permission\" class=\"col-sm-2 control-label\">View Patie" +
"nts:</label>\r\n                <div class=\"col-sm-5\">\r\n                    <selec" +
"t class=\"form-control\" id=\"suggestion-box-manage-permission\" disabled>\r\n        " +
"                <option value=\"\">Loading...</option>\r\n                    </sele" +
"ct>\r\n                </div>\r\n            </div>\r\n\r\n        </div>\r\n\r\n    </div>\r" +
"\n    <% } %>\r\n    <div class=\"collapse\" id=\"collapseAdvancedSearch\"></div>\r\n</sc" +
"ript>\r\n");

        }
    }
}
#pragma warning restore 1591
