#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Maestro.Web;
    using Maestro.Web.Areas.Site;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Site/Views/Patients/Templates/PatientCalendarProgramTerminateModalTemplat" +
        "e.cshtml")]
    public partial class _Areas_Site_Views_Patients_Templates_PatientCalendarProgramTerminateModalTemplate_cshtml : Maestro.Web.BaseViewPage<dynamic>
    {
        public _Areas_Site_Views_Patients_Templates_PatientCalendarProgramTerminateModalTemplate_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" id=\"patientCalendarProgramTerminateModalTemplate\"");

WriteLiteral(" type=\"text/template\"");

WriteLiteral(@">
    <div class=""alert alert-danger hidden"" role=""alert""></div>
    <div class=""form-horizontal"">
        <div class=""form-group"">
            <label for=""termination"" class=""col-sm-3 control-label"">Terminate On</label>
            <div class=""col-sm-4"">
                <div id=""termination-datetimepicker"" class=""input-group"">
                    <input type=""text"" class=""form-control"" id=""terminationDp"" name=""terminationDp"">
                    <span class=""input-group-addon"">
                        <span class=""glyphicon glyphicon-calendar""></span>
                    </span>
                </div>
                <input type=""hidden"" id=""terminationUtc"" name=""terminationUtc"">
            </div>
        </div>
    </div>
</script>");

        }
    }
}
#pragma warning restore 1591
