#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Maestro.Web;
    using Maestro.Web.Areas.Site;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Site/Views/Patients/Templates/PatientTrendsAddChartsViewTemplate.cshtml")]
    public partial class _Areas_Site_Views_Patients_Templates_PatientTrendsAddChartsViewTemplate_cshtml : Maestro.Web.BaseViewPage<dynamic>
    {
        public _Areas_Site_Views_Patients_Templates_PatientTrendsAddChartsViewTemplate_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" id=\"patientTrendsAddChartsViewTemplate\"");

WriteLiteral(" type=\"text/template\"");

WriteLiteral(">\r\n\r\n    <div class=\"row\">\r\n        <div class=\"col-sm-12\">\r\n            <div cla" +
"ss=\"btn-group\">\r\n                <button type=\"button\" class=\"btn btn-default js" +
"-show-vitals\">Measurements</button>\r\n                <button type=\"button\" class" +
"=\"btn btn-default js-show-questions\">Care Elements</button>\r\n            </div>\r" +
"\n        </div>\r\n    </div>\r\n    <br>\r\n\r\n    <div class=\"row\">\r\n        <div cla" +
"ss=\"col-sm-6 charts-list-container\">\r\n            <ul class=\"list-group chart-ty" +
"pes\">\r\n                <% _.each(availableCharts, function (chartMeta, index) { " +
"%>\r\n                <li class=\"list-group-item chart-item\">\r\n                   " +
" <span class=\"chart-title\" title=\"<%=chartMeta.label%>\"><%=chartMeta.label%></sp" +
"an>\r\n                    <a href=\"\" class=\"js-add-chart\" data-index=\"<%=index%>\"" +
">Add</a>\r\n                </li>\r\n                <% }); %>\r\n            </ul>\r\n " +
"       </div>\r\n        <div class=\"col-sm-6\">\r\n            <ul class=\"list-group" +
" chart-types\">\r\n                <% _.each(selectedCharts, function (chartMeta, i" +
"ndex) { %>\r\n                    <li class=\"list-group-item chart-item\">\r\n       " +
"                 <span class=\"chart-title\" title=\"<%=chartMeta.label%>\"><span><%" +
"=chartMeta.label%></span></span>\r\n                        <span class=\"actions\">" +
"\r\n                            <button class=\"js-move-up\" data-index=\"<%=index%>\"" +
">&#8593;</button>\r\n                            <button class=\"js-move-down\" data" +
"-index=\"<%=index%>\">&#8595;</button>\r\n                        </span>\r\n         " +
"               <a href=\"\" class=\"js-remove-chart\" data-index=\"<%=index%>\">Remove" +
"</a>\r\n                    </li>\r\n                <% }); %>\r\n            </ul>\r\n " +
"       </div>\r\n    </div>\r\n</script>");

        }
    }
}
#pragma warning restore 1591
