#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Maestro.Web;
    using Maestro.Web.Areas.Site;
    
    #line 1 "..\..\Areas\Site\Views\Patients\Templates\PatientViewTemplate.cshtml"
    using Maestro.Web.Resources;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Site/Views/Patients/Templates/PatientViewTemplate.cshtml")]
    public partial class _Areas_Site_Views_Patients_Templates_PatientViewTemplate_cshtml : Maestro.Web.BaseViewPage<dynamic>
    {
        public _Areas_Site_Views_Patients_Templates_PatientViewTemplate_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<script");

WriteLiteral(" id=\"patientViewTemplate\"");

WriteLiteral(" type=\"text/template\"");

WriteLiteral(@">
    <div class=""page-header page-header-ci page-header-primary-ci"">
        <div class=""pull-right"">
            <a href=""EditPatient/<%=id%>/PatientInfo/"" class=""btn btn-primary btn-lg btn-invert js-patient-edit"">Edit</a>
        </div>
        <h1>
            <%=firstName%>
            <%=lastName%>
            <% if( idMain ){ %><small>(<%=idMain.value%>)</small><% } %>
        </h1>
    </div>
    <div class=""page-content-ci"">

        <div class=""b-patient-card-ci"">
            
            <div class=""well patient-card-info-ci"">
                <div class=""row"">
                    <div class=""col-sm-1""><strong>");

            
            #line 20 "..\..\Areas\Site\Views\Patients\Templates\PatientViewTemplate.cshtml"
                                             Write(GlobalStrings.Patient_Age);

            
            #line default
            #line hidden
WriteLiteral("</strong> <%=age%></div>\r\n                    <div class=\"col-sm-2\"><strong>");

            
            #line 21 "..\..\Areas\Site\Views\Patients\Templates\PatientViewTemplate.cshtml"
                                             Write(GlobalStrings.Patient_View_DateOfBirth);

            
            #line default
            #line hidden
WriteLiteral("</strong> <%=birthDateParsed%></div>\r\n                    <div class=\"col-sm-2\"><" +
"strong>");

            
            #line 22 "..\..\Areas\Site\Views\Patients\Templates\PatientViewTemplate.cshtml"
                                             Write(GlobalStrings.Patient_View_Gender);

            
            #line default
            #line hidden
WriteLiteral("</strong> <%=genderName%></div>\r\n                    <div class=\"col-sm-3\"><stron" +
"g>");

            
            #line 23 "..\..\Areas\Site\Views\Patients\Templates\PatientViewTemplate.cshtml"
                                             Write(GlobalStrings.Patient_View_Phone);

            
            #line default
            #line hidden
WriteLiteral(@"</strong> <%=phoneHome%></div>
                    <div class=""col-sm-4 text-right action-list"">
                        <a class=""js-chat"">
                            <i class=""fa fa-envelope fa-invert-ci""></i>
                            Send Message
                        </a>
                        <a class=""js-video-call"">
                            <i class=""fa fa-video-camera fa-invert-ci""></i>
                            Start Video Call
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <div class=""b-patient-additional-info-ci"">

            <div class=""row row-patient-info-ci"">
                <div class=""col-sm-3"">
                    <h4>");

            
            #line 42 "..\..\Areas\Site\Views\Patients\Templates\PatientViewTemplate.cshtml"
                   Write(GlobalStrings.Patient_KeyIdentifiersText);

            
            #line default
            #line hidden
WriteLiteral(@"</h4>
                    <ul class=""list-unstyled"">
                    <% _.each(identifiers, function(identifier){ %>
                        <li><%= identifier.name %>: <%= identifier.value %></li>
                    <% }); %>
                    </ul>
                </div>
                <div class=""col-sm-3"">
                    <h4>");

            
            #line 50 "..\..\Areas\Site\Views\Patients\Templates\PatientViewTemplate.cshtml"
                   Write(GlobalStrings.Patients_CareManagersText);

            
            #line default
            #line hidden
WriteLiteral(@"</h4>
                     <div id=""assigned-care-managers-container""></div>
                    <!--if (User.IsInRole(Roles.SuperAdminRoleName) ||
                                 User.HasPermissions(CustomerContext.Current.Customer.Id,
                                     CustomerUserRolePermissions.AssignRemoveCareManagers))-->
                    <a class=""js-patient-edit"" href=""EditPatient/<%=id%>/CareManagers/"">
");

WriteLiteral("                        ");

            
            #line 56 "..\..\Areas\Site\Views\Patients\Templates\PatientViewTemplate.cshtml"
                   Write(GlobalStrings.Patient_View_AddCareManagerLink);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </a>\r\n                </div>\r\n                <div class=\"c" +
"ol-sm-3\">\r\n                    <h4>");

            
            #line 60 "..\..\Areas\Site\Views\Patients\Templates\PatientViewTemplate.cshtml"
                   Write(GlobalStrings.Patient_PatientDemographicsText);

            
            #line default
            #line hidden
WriteLiteral(@"</h4>
                    <ul class=""list-unstyled"">
                        <li><%=address1%></li>
                        <% if ( address2 ) { %><li><%=address2%></li><% } %>
                        <% if ( address3 ) { %><li><%=address3%></li><% } %>
                        <li><%=city%>, <%=state%>, <%=zipCode%></li>
                        <li><%=phoneHome%> (home)<% if ( phoneWork ){%> | <%=phoneWork%> (work)<% } %></li>
                        <% if ( email ) { %><li><a href=""mailto:<%=email%>""><%=email%></a></li><% } %>
                        <li>Language: <%=language%></li>
                    </ul>           
                </div>
                <div class=""col-sm-3"">
                    <h4>");

            
            #line 72 "..\..\Areas\Site\Views\Patients\Templates\PatientViewTemplate.cshtml"
                   Write(GlobalStrings.Patient_ConditionsTitle);

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n                    \r\n                    <div id=\"js-patient-conditions-c" +
"ontainer\"></div>\r\n                    \r\n                    <a class=\"js-patient" +
"-edit\" href=\"EditPatient/<%=id%>/Conditions/\">\r\n");

WriteLiteral("                        ");

            
            #line 77 "..\..\Areas\Site\Views\Patients\Templates\PatientViewTemplate.cshtml"
                   Write(GlobalStrings.Patient_View_AddConditionLink);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </a>\r\n                </div>\r\n            </div>\r\n\r\n       " +
"     <!--div class=\"row row-patient-info-ci\">\r\n                <div class=\"col-s" +
"m-4\">\r\n                    <h4>");

            
            #line 84 "..\..\Areas\Site\Views\Patients\Templates\PatientViewTemplate.cshtml"
                   Write(GlobalStrings.Patient_View_FamilyCaregiver);

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n                </div>\r\n                <div class=\"col-sm-4\">\r\n          " +
"          <h4>");

            
            #line 87 "..\..\Areas\Site\Views\Patients\Templates\PatientViewTemplate.cshtml"
                   Write(GlobalStrings.Patients_GroupsAndConditionsText);

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n                    <a class=\"btn btn-primary\">\r\n                        <" +
"span class=\"glyphicon glyphicon-plus\"></span>\r\n");

WriteLiteral("                        ");

            
            #line 90 "..\..\Areas\Site\Views\Patients\Templates\PatientViewTemplate.cshtml"
                   Write(GlobalStrings.Patient_View_AssignGroupLink);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </a>\r\n                </div>\r\n                <div class=\"c" +
"ol-sm-4\">\r\n                    <h4>");

            
            #line 94 "..\..\Areas\Site\Views\Patients\Templates\PatientViewTemplate.cshtml"
                   Write(GlobalStrings.Patient_View_Physicians);

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n                </div>\r\n            </div-->\r\n        </div>\r\n\r\n        <d" +
"iv class=\"b-patient-additional-info-controll-ci\">\r\n            <a class=\"btn-tog" +
"gle-slide js-patient-additional-info-toggle\">\r\n                <span class=\"fa f" +
"a-angle-down\"></span>\r\n                <!--span class=\"glyphicon glyphicon-chevr" +
"on-up\"></span-->\r\n            </a>    \r\n        </div>\r\n\r\n        <div style=\"po" +
"sition: relative;\">\r\n            <ul class=\"nav nav-tabs nav-tabs-primary\">\r\n   " +
"             <li>\r\n                    <a href=\"#dashboard\" id=\"Dashboard\" data-" +
"href=\"PatientDetails/<%=id%>/Dashboard/\" class=\"js-view-patient-tab\">\r\n         " +
"               Patient Dashboard\r\n                    </a>\r\n                </li" +
">\r\n                <li>\r\n                    <a href=\"#schedule\" id=\"Schedule\" d" +
"ata-href=\"PatientDetails/<%=id%>/Schedule/\" class=\"js-view-patient-tab\">\r\n      " +
"                  Schedule\r\n                    </a>\r\n                </li>\r\n   " +
"             <li>\r\n                    <a href=\"#detailedData\" id=\"DetailedData\"" +
" data-href=\"PatientDetails/<%=id%>/DetailedData/\" class=\"js-view-patient-tab\" >\r" +
"\n                        Detailed Data\r\n                    </a>\r\n              " +
"  </li>\r\n                <li>\r\n                    <a href=\"#trends\" id=\"Trends\"" +
" data-href=\"PatientDetails/<%=id%>/Trends/\" class=\"js-view-patient-tab\">\r\n      " +
"                  Trends\r\n                    </a>\r\n                </li>\r\n     " +
"           <!--li>\r\n                    <a href=\"#history\" id=\"History\" data-hre" +
"f=\"PatientDetails/<%=id%>/History/\" class=\"js-view-patient-tab\">Patient History<" +
"/a>\r\n                </li-->\r\n            </ul>\r\n            <div class=\"tab-con" +
"tent\">\r\n                <div id=\"dashboard\" class=\"tab-pane\" role=\"tabpanel\"></d" +
"iv>\r\n                <div id=\"schedule\" class=\"tab-pane\" role=\"tabpanel\"></div>\r" +
"\n                <div id=\"detailedData\" class=\"tab-pane\" role=\"tabpanel\"></div>\r" +
"\n                <div id=\"trends\" class=\"tab-pane\" role=\"tabpanel\"></div>\r\n     " +
"           <div id=\"history\" class=\"tab-pane\" role=\"tabpanel\"></div>       \r\n   " +
"         </div>\r\n            <button id=\"show-patient-notes\" style=\"position: ab" +
"solute;top: 0;right: 0;\" type=\"button\" class=\"btn btn-success btn-sm\">\r\n        " +
"        <i class=\"fa fa-book\"></i>\r\n            </button>\r\n        </div>\r\n    <" +
"/div>\r\n</script>");

        }
    }
}
#pragma warning restore 1591
