#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Maestro.Web;
    using Maestro.Web.Areas.Site;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Site/Views/Patients/Templates/PatientTrendsVitalChartViewTemplate.cshtml")]
    public partial class _Areas_Site_Views_Patients_Templates_PatientTrendsVitalChartViewTemplate_cshtml : Maestro.Web.BaseViewPage<dynamic>
    {
        public _Areas_Site_Views_Patients_Templates_PatientTrendsVitalChartViewTemplate_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" id=\"patientTrendsVitalChartViewTemplate\"");

WriteLiteral(" type=\"text/template\"");

WriteLiteral(">\r\n    <li class=\"chart-container col-sm-6\">\r\n        <div class=\"pull-right\">\r\n " +
"           <a class=\"js-reorder\">\r\n                <i class=\"fa fa-bars fa-inver" +
"t-ci\"></i>\r\n                Reorder\r\n            </a>\r\n            &nbsp;\r\n     " +
"       <a class=\"js-remove\">\r\n                <i class=\"fa fa-times fa-invert-ci" +
"\"></i>\r\n                Remove\r\n            </a>\r\n            <!--span><small>Mo" +
"ve chart</small></span>\r\n            <button class=\"js-move-up\">&#8593;</button>" +
"\r\n            <button class=\"js-move-down\">&#8595;</button-->\r\n        </div>\r\n " +
"       <h3><%=chartLabel%></h3>\r\n        <div class=\"clearfix\"></div>\r\n        <" +
"div class=\"chart\"></div>\r\n        <span class=\"chart-settings\">\r\n            <sp" +
"an class=\"data-series\">\r\n                <label>\r\n                    <input typ" +
"e=\"checkbox\" class=\"js-toggle-max\">\r\n                    Max\r\n                </" +
"label>\r\n                <label>\r\n                    <input type=\"checkbox\" clas" +
"s=\"js-toggle-avg\">\r\n                    Avg\r\n                </label>\r\n         " +
"       <label>\r\n                    <input type=\"checkbox\" class=\"js-toggle-min\"" +
">\r\n                    Min\r\n                </label>\r\n            </span>\r\n     " +
"       <span class=\"thresholds-series\">\r\n                <% _.each(thresholds, f" +
"unction (threshold) { %>\r\n                    <label>\r\n                        <" +
"input type=\"checkbox\" class=\"js-toggle-threshold\" data-threshold-id=\"<%= thresho" +
"ld.id %>\">\r\n                        <%= threshold.alertSeverity ? threshold.aler" +
"tSeverity.name : \'\' %> threshold\r\n                    </label>\r\n                " +
"<% }) %>\r\n            </span>\r\n        </span>\r\n        <div class=\"spinner-cont" +
"ainer\" style=\"display: none;\">\r\n            <img src=\"/Content/img/spinner.gif\" " +
"class=\"spinner\" />\r\n        </div>\r\n    </li>\r\n</script>");

        }
    }
}
#pragma warning restore 1591
