#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Maestro.Web;
    using Maestro.Web.Areas.Site;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Site/Views/Patients/Templates/PatientsListItemDetailsTemplate.cshtml")]
    public partial class _Areas_Site_Views_Patients_Templates_PatientsListItemDetailsTemplate_cshtml : Maestro.Web.BaseViewPage<dynamic>
    {
        public _Areas_Site_Views_Patients_Templates_PatientsListItemDetailsTemplate_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" id=\"patientsListItemDetailsTemplate\"");

WriteLiteral(" type=\"text/template\"");

WriteLiteral(@">
    <h5>Programs:</h5>
    <div class=""row patient-search-wrapper"">
        <% if(obj.Programs.length) { %>
            <% _.each(obj.Programs, function(program) { %>
            <div class=""col-sm-4 patient-search-col"">
                <div class=""patient-search-program""><%- program.Name %> (Day <%- program.CurrentDay %> of <%- program.TotalDays %>)</div>
            </div>
            <% }) %>
        <% } else { %>
            <div class=""col-sm-12 patient-search-no-col"">
                <div class=""well well-sm"">No Programs</div>
            </div>
        <% } %>
    </div>
</script>");

        }
    }
}
#pragma warning restore 1591
