#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Maestro.Web;
    using Maestro.Web.Areas.Site;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Site/Views/Patients/Templates/PatientDetailedDataViewTemplate.cshtml")]
    public partial class _Areas_Site_Views_Patients_Templates_PatientDetailedDataViewTemplate_cshtml : Maestro.Web.BaseViewPage<dynamic>
    {
        public _Areas_Site_Views_Patients_Templates_PatientDetailedDataViewTemplate_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" id=\"patientDetailedDataViewTemplate\"");

WriteLiteral(" type=\"text/template\"");

WriteLiteral(">\r\n    <div class=\"patient-detailed-data clearfix\">\r\n        ");

WriteLiteral(@"
        <div class=""row js-detailed-data-date-filter""></div>
        <div class=""row"">
            <div class=""col-sm-3 pull-left"">
                <div class=""checkbox"">
                    <label>
                        <input type=""checkbox"" name=""isGrouped"" id=""isGrouped"" class=""js-grouped"">
                        Group by Health Session
                    </label>
                </div>
            </div>
            <div class=""col-sm-3 pull-right text-right"">
                <div class=""js-accordion-collapse-trigger"">
                    <a class=""js-expand-all"">Expand All</a>
                    &emsp;
                    <a class=""js-collapse-all"">Collapse All</a>
                </div>
            </div>
        </div>
        <div class=""row"">
            <div class=""col-sm-3 pull-right text-right"">
                <a href=""#"" class=""disabled js-patient-export-detailed-data"">
                    <i class=""fa fa-external-link fa-invert-ci""></i>
                    Export detailed data
                </a>
            </div>
        </div>
        <br>
        <div class=""b-detailed-data js-detailed-data""></div>
        <div class=""b-detailed-data-hint text-right"">
            <span class=""italic has-asterisk"">
                manual entry
            </span>
        </div>
    </div>
</script>");

        }
    }
}
#pragma warning restore 1591
