#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Maestro.Web;
    using Maestro.Web.Areas.Site;
    
    #line 1 "..\..\Areas\Site\Views\Patients\Templates\PatientCreateTemplate.cshtml"
    using Maestro.Web.Resources;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Site/Views/Patients/Templates/PatientCreateTemplate.cshtml")]
    public partial class _Areas_Site_Views_Patients_Templates_PatientCreateTemplate_cshtml : Maestro.Web.BaseViewPage<dynamic>
    {
        public _Areas_Site_Views_Patients_Templates_PatientCreateTemplate_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<script");

WriteLiteral(" id=\"patientCreateTemplate\"");

WriteLiteral(" type=\"text/template\"");

WriteLiteral(@">
	<div class=""page-header page-header-ci page-header-primary-ci"">
		<h1>Create Patient</h1>
	</div>

	<div class=""page-content-ci"">
		<ul class=""nav nav-tabs"">
			<li class=""active""><a>Patient Info</a></li>
			<li class=""tab-disabled-ci""><a>Care Managers</a></li>
			<!--li class=""tab-disabled-ci""><a>Groups and Conditions</a></li-->
			<li class=""tab-disabled-ci""><a>");

            
            #line 13 "..\..\Areas\Site\Views\Patients\Templates\PatientCreateTemplate.cshtml"
                                      Write(GlobalStrings.PatientLayout_ThresholdsTabText);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n\t\t\t<li class=\"tab-disabled-ci\"><a>Devices</a></li>\r\n\t\t</ul>\r\n\r\n\t\t<div " +
"class=\"tab-content\">\r\n\t\t\t<div id=\"patient-info\" class=\"tab-pane active\">\r\n\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 20 "..\..\Areas\Site\Views\Patients\Templates\PatientCreateTemplate.cshtml"
           Write(Html.Partial("Templates/_PatientEditInfoTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\t\t\t</div>\r\n\t\t</div>\r\n\t</div>\r\n</script>");

        }
    }
}
#pragma warning restore 1591
