#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Maestro.Web;
    using Maestro.Web.Areas.Site;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Site/Views/Patients/Templates/PatientsListItemTemplate.cshtml")]
    public partial class _Areas_Site_Views_Patients_Templates_PatientsListItemTemplate_cshtml : Maestro.Web.BaseViewPage<dynamic>
    {
        public _Areas_Site_Views_Patients_Templates_PatientsListItemTemplate_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" id=\"patientsListItemTemplate\"");

WriteLiteral(" type=\"text/template\"");

WriteLiteral(">\r\n    <header data-toggle=\"collapse\" class=\"panel-heading\">\r\n        <div class=" +
"\"row\">\r\n            <div class=\"col-sm-5\">\r\n                <a class=\"btn btn-de" +
"fault  btn-xs btn-radius-ci indicator\">\r\n                    <i class=\"fa fa-ang" +
"le-down\"></i>\r\n                </a>\r\n                <a class=\"panel-heading-tex" +
"t js-patient-show\" href=\"PatientDetails/<%=Id%>/\">\r\n                    <%- obj." +
"FirstName %> <%- obj.LastName %>  <% if(obj.Identifiers.length) { %> \r\n         " +
"               <% var primaryIdentifier = _.find(obj.Identifiers, function(item)" +
" { return item.IsPrimary; }) %>\r\n                        <% if (primaryIdentifie" +
"r) { %>\r\n                            (<%- primaryIdentifier.Value %>)\r\n         " +
"               <% } %>\r\n                    <% } %>\r\n                </a>\r\n     " +
"       </div>\r\n            <div class=\"col-sm-2\">\r\n                <% if(obj.Sta" +
"tus.code === 0) { %>\r\n                    <i><%- obj.Status.name %></i>\r\n       " +
"         <% } else if(obj.Status.code === 2) { %>\r\n                    <span><%-" +
" obj.Status.name %></span>\r\n                <% } %>\r\n            </div>\r\n       " +
"     <div class=\"col-sm-5\">\r\n                <div class=\"row\">\r\n                " +
"    <div class=\"col-sm-6 text-right\">\r\n                        <strong>Care Mana" +
"gers:</strong>\r\n                    </div>\r\n                    <div class=\"col-" +
"sm-6\">\r\n                        <% _.each(obj.CareManagers, function(careManager" +
", counter) { %>\r\n                            <div><%=careManager.FirstName %> <%" +
"=careManager.LastName %></div>\r\n                        <% }); %>\r\n             " +
"       </div>\r\n                </div>\r\n            </div>\r\n        </div>\r\n    <" +
"/header>\r\n    <div class=\"panel-collapse collapse\">\r\n        <div class=\"panel-b" +
"ody\">\r\n            <img src=\"/Content/img/spinner.gif\" class=\"spinner\" />\r\n     " +
"   </div>\r\n    </div>\r\n</script>");

        }
    }
}
#pragma warning restore 1591
