// <auto-generated />
namespace CustomerService.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Site_AddField_Subdomain : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Site_AddField_Subdomain));
        
        string IMigrationMetadata.Id
        {
            get { return "201504131051303_Site_AddField_Subdomain"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
