// <auto-generated />
namespace CustomerService.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Indexbynameandcutomerid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Indexbynameandcutomerid));
        
        string IMigrationMetadata.Id
        {
            get { return "201601192032359_Index by name and cutomerid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
