#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Maestro.Web;
    using Maestro.Web.Areas.Site;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Site/Views/Dashboard/Templates/PatientViewDetailsBehavior.cshtml")]
    public partial class _Areas_Site_Views_Dashboard_Templates_PatientViewDetailsBehavior_cshtml : Maestro.Web.BaseViewPage<dynamic>
    {
        public _Areas_Site_Views_Dashboard_Templates_PatientViewDetailsBehavior_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" id=\"patientCardViewTemplateDetailBEHAVIOR\"");

WriteLiteral(" type=\"text/template\"");

WriteLiteral(">\r\n    <% if(!obj.noColor) { %>\r\n    <span class=\"color-line\" style=\"background: " +
"transparent\"></span>\r\n    <% } else { %>\r\n    <span class=\"color-line\" style=\"ba" +
"ckground: <%- obj.color %>\"></span>\r\n    <% } %>\r\n    <div class=\"alert-detailed" +
"-body collapse\" id=\"details-<%- obj.id %>\">\r\n        <div class=\"row alert-detai" +
"ls-container\">\r\n            <div class=\"col-sm-4\">\r\n                <div class=\"" +
"block\">\r\n                    <h5>Answer:</h5>\r\n                    <hr style=\"ma" +
"rgin-top: 0;margin-bottom: 15px;border-top:1px solid #ddd;\"/>\r\n                 " +
"   <div class=\"row\">\r\n                        <div class=\"col-sm-12\" style=\"over" +
"flow: hidden; text-overflow: ellipsis\" title=\"<%- obj.reading.answerText %>\"><sp" +
"an style=\"color: <%- obj.color %>;\"><%- obj.reading.answerText %></span></div>\r\n" +
"                    </div>\r\n                </div>\r\n            </div>\r\n        " +
"    <div class=\"col-sm-5\" style=\"overflow: hidden; text-overflow: ellipsis;\">\r\n " +
"               <% if(obj.recentReadings) if(obj.recentReadings.length) { %>\r\n   " +
"             <h5>Recent Answers (last 30 days):</h5>\r\n                <table cla" +
"ss=\"table table-striped\">\r\n                    <tbody>\r\n                    <% _" +
".each(obj.recentReadings, function(recentReading) { %>\r\n                    <tr>" +
"\r\n                        <td style=\"white-space: nowrap\"><%- recentReading.firs" +
"t %></td>\r\n                        <td style=\"white-space: nowrap\"><%- recentRea" +
"ding.second %></td>\r\n                        <td class=\"text-right\"><strong styl" +
"e=\"color:<%- recentReading.color %>;\" title=\"<%- recentReading.answerText %>\"><%" +
"- recentReading.answerText %></strong></td>\r\n                    </tr>\r\n        " +
"            <% }) %>\r\n                    </tbody>\r\n                </table>\r\n  " +
"              <% } else { %>\r\n                <div class=\"well text-center\">No a" +
"nswers were reported in the last 30 days</div>\r\n                <% } %>\r\n       " +
"     </div>\r\n            <div class=\"col-sm-3\">\r\n                <h5>Contact pat" +
"ient:</h5>\r\n                <hr style=\"margin-top: 0;\"/>\r\n                <% if(" +
"obj.patientInfo.phone) { %>\r\n                <h5 style=\"margin-bottom: 0;\">Phone" +
" number:</h5>\r\n                <%- obj.patientInfo.phone %> <br/><br/>\r\n        " +
"        <% } %>\r\n                <a href=\"#\" class=\"js-video\"><i class=\"fa fa-ic" +
"on fa-video-camera\"></i> Start video call</a>\r\n                <br/>\r\n          " +
"      <br/>\r\n                <a href=\"#\" class=\"js-chat\"><i class=\"fa fa-icon fa" +
"-envelope\"></i> Send Message</a>\r\n                <br/>\r\n            </div>\r\n   " +
"     </div>\r\n        <div class=\"row alert-details-container\">\r\n            <div" +
" class=\"col-sm-5\">\r\n                <div class=\"row\">\r\n                    <div " +
"class=\"col-sm-6\">\r\n                        <p>\r\n                            <but" +
"ton type=\"button\" class=\"btn btn-default acknowledge-alert\">Acknowledge</button>" +
"\r\n                        </p>\r\n                    </div>\r\n                    " +
"<div class=\"col-sm-6 text-right\">\r\n                        <!--<p class=\"watch-p" +
"atient-wrapper\"></p>-->\r\n                    </div>\r\n                </div>\r\n   " +
"         </div>\r\n            <div class=\"col-sm-4\">\r\n                <% if(obj.h" +
"asMore) { %>\r\n                <div class=\"row\">\r\n                    <div class=" +
"\"col-sm-6\">\r\n                        <i style=\"display: inline-block;margin-top:" +
" 5px;\">(+<%- obj.hasMore %> see more)</i>\r\n                    </div>\r\n         " +
"           <div class=\"col-sm-6\">\r\n                        <a role=\"button\" clas" +
"s=\"btn btn-primary pull-right\" href=\"<%- obj.url %>/Patients/PatientDetails/<%- " +
"obj.patientInfo.id %>/DetailedData/\">See more</a>\r\n                    </div>\r\n " +
"               </div>\r\n                <% } %>\r\n            </div>\r\n            " +
"<div class=\"col-sm-3\"></div>\r\n        </div>\r\n    </div>\r\n</script>");

        }
    }
}
#pragma warning restore 1591
