#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Maestro.Web;
    using Maestro.Web.Areas.Site;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Site/Views/Dashboard/Templates/PatientViewDetailsBloodPressure.cshtml")]
    public partial class _Areas_Site_Views_Dashboard_Templates_PatientViewDetailsBloodPressure_cshtml : Maestro.Web.BaseViewPage<dynamic>
    {
        public _Areas_Site_Views_Dashboard_Templates_PatientViewDetailsBloodPressure_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" id=\"patientCardViewTemplateDetailBloodPressure\"");

WriteLiteral(" type=\"text/template\"");

WriteLiteral(">\r\n    <% if(!obj.noColor) { %>\r\n    <span class=\"color-line\" style=\"background: " +
"transparent\"></span>\r\n    <% } else { %>\r\n    <span class=\"color-line\" style=\"ba" +
"ckground: <%- obj.color %>\"></span>\r\n    <% } %>\r\n    <div class=\"alert-detailed" +
"-body collapse\" id=\"details-<%= (obj.reading.measurement.vitals.systolicBloodPre" +
"ssure.id ? obj.reading.measurement.vitals.systolicBloodPressure.id : obj.reading" +
".measurement.vitals.diastolicBloodPressure.id) %>\">\r\n        <div class=\"row ale" +
"rt-details-container\">\r\n            <div class=\"col-sm-5\">\r\n                <div" +
" class=\"block\">\r\n                    <h5>Reading:</h5>\r\n                    <hr " +
"style=\"margin-top: 0;margin-bottom: 15px;border-top:1px solid #ddd;\"/>\r\n        " +
"            <div class=\"row\">\r\n                        <div class=\"col-sm-6\">\r\n " +
"                           <h4 style=\"display: inline-block;margin: 0;\">\r\n      " +
"                          <% if(!obj.reading.isAutomated) { %>*<% } %><span styl" +
"e=\"color: <%- obj.reading.measurement.vitals.systolicBloodPressure.color %>;\"><%" +
"- obj.reading.measurement.vitals.systolicBloodPressure.value %></span>/<span sty" +
"le=\"color: <%- obj.reading.measurement.vitals.diastolicBloodPressure.color %>;\">" +
"<%- obj.reading.measurement.vitals.diastolicBloodPressure.value %></span>\r\n     " +
"                       </h4> <%- obj.unitLabel %>\r\n                        </div" +
">\r\n                        <div class=\"col-sm-6 text-right\">\r\n                  " +
"          <a class=\"ignore-reading\" style=\"margin-top: 10px;\" href=\"#\"><i class=" +
"\"fa fa-icon fa-times\"></i> Ignore Reading</a>\r\n                        </div>\r\n " +
"                   </div>\r\n                </div>\r\n                <div class=\"b" +
"lock\" style=\"margin: 20px 0;\">\r\n                    <h5>Threshold:</h5>\r\n       " +
"             <hr style=\"margin-top: 0;margin-bottom: 15px;border-top:1px solid #" +
"ddd;\"/>\r\n                    <div class=\"row\">\r\n                        <div cla" +
"ss=\"col-sm-12\">\r\n                            <% if(obj.reading.measurement.vital" +
"s.systolicBloodPressure.vitalAlert) { %>\r\n                            <div>\r\n   " +
"                             <strong>Systolic Blood Pressure</strong>&nbsp;\r\n   " +
"                             <strong style=\"color: <%- obj.reading.measurement.v" +
"itals.systolicBloodPressure.color %>;\"><%- obj.reading.measurement.vitals.systol" +
"icBloodPressure.isHigher ? \'higher\' : \'lower\' %></strong> than\r\n                " +
"                <h4 style=\"display: inline-block;margin: 0;\"><%- obj.reading.mea" +
"surement.vitals.systolicBloodPressure.isHigher ? obj.reading.measurement.vitals." +
"systolicBloodPressure.vitalAlert.violatedThreshold.maxValue : obj.reading.measur" +
"ement.vitals.systolicBloodPressure.vitalAlert.violatedThreshold.minValue  %></h4" +
"> <%- obj.unitLabel %>\r\n                            </div>\r\n                    " +
"        <% } %>\r\n                            <% if(obj.reading.measurement.vital" +
"s.diastolicBloodPressure.vitalAlert) { %>\r\n                            <div>\r\n  " +
"                              <strong>Diastolic Blood Pressure</strong>&nbsp;\r\n " +
"                               <strong style=\"color: <%- obj.reading.measurement" +
".vitals.diastolicBloodPressure.color %>;\"><%- obj.reading.measurement.vitals.dia" +
"stolicBloodPressure.isHigher ? \'higher\' : \'lower\' %></strong> than\r\n            " +
"                    <h4 style=\"display: inline-block;margin: 0;\"><%- obj.reading" +
".measurement.vitals.diastolicBloodPressure.isHigher ? obj.reading.measurement.vi" +
"tals.diastolicBloodPressure.vitalAlert.violatedThreshold.maxValue : obj.reading." +
"measurement.vitals.diastolicBloodPressure.vitalAlert.violatedThreshold.minValue " +
" %></h4> <%- obj.unitLabel %>\r\n                            </div>\r\n             " +
"               <% } %>\r\n                        </div>\r\n                    </di" +
"v>\r\n                </div>\r\n            </div>\r\n            <div class=\"col-sm-4" +
"\">\r\n                <% if(obj.recentReadings) if(obj.recentReadings.length) { %>" +
"\r\n                <h5>Recent Readings (last 30 days):</h5>\r\n                <tab" +
"le class=\"table table-striped\">\r\n                    <tbody>\r\n                  " +
"  <% _.each(obj.recentReadings, function(recentReading) { %>\r\n                  " +
"  <tr>\r\n                        <td style=\"white-space: nowrap\"><%- recentReadin" +
"g.measurement.vitals.systolicBloodPressure.first %></td>\r\n                      " +
"  <td style=\"white-space: nowrap\"><%- recentReading.measurement.vitals.systolicB" +
"loodPressure.second %></td>\r\n                        <td>\r\n                     " +
"       <strong>\r\n                                <% if(!recentReading.measuremen" +
"t.isAutomated) { %>*<% } %><span style=\"color: <%- recentReading.measurement.vit" +
"als.systolicBloodPressure.color %>\"><%- recentReading.measurement.vitals.systoli" +
"cBloodPressure.value %></span>/<span style=\"color: <%- recentReading.measurement" +
".vitals.diastolicBloodPressure.color %>\"><%- recentReading.measurement.vitals.di" +
"astolicBloodPressure.value %></span>\r\n                            </strong>\r\n   " +
"                     </td>\r\n                    </tr>\r\n                    <% })" +
" %>\r\n                    </tbody>\r\n                </table>\r\n                <% " +
"} else { %>\r\n                <div class=\"well text-center\">No readings were repo" +
"rted in the last 30 days</div>\r\n                <% } %>\r\n            </div>\r\n   " +
"         <div class=\"col-sm-3\">\r\n                <h5>Contact patient:</h5>\r\n    " +
"            <hr style=\"margin-top: 0;\"/>\r\n                <% if(obj.patientInfo." +
"phone) { %>\r\n                <h5 style=\"margin-bottom: 0;\">Phone number:</h5>\r\n " +
"               <%- obj.patientInfo.phone %> <br/><br/>\r\n                <% } %>\r" +
"\n                <a href=\"#\" class=\"js-video\"><i class=\"fa fa-icon fa-video-came" +
"ra\"></i> Start video call</a>\r\n                <br/>\r\n                <br/>\r\n   " +
"             <a href=\"#\" class=\"js-chat\"><i class=\"fa fa-icon fa-envelope\"></i> " +
"Send Message</a>\r\n                <br/>\r\n            </div>\r\n        </div>\r\n   " +
"     <div class=\"row alert-details-container\">\r\n            <div class=\"col-sm-5" +
"\">\r\n                <div class=\"row\">\r\n                    <div class=\"col-sm-6\"" +
">\r\n                        <p>\r\n                            <button type=\"button" +
"\" class=\"btn btn-default acknowledge-alert\">Acknowledge</button>\r\n              " +
"          </p>\r\n                    </div>\r\n                    <div class=\"col-" +
"sm-6 text-right\">\r\n                        <!--<p class=\"watch-patient-wrapper\">" +
"</p>-->\r\n                    </div>\r\n                </div>\r\n            </div>\r" +
"\n            <div class=\"col-sm-4\">\r\n                <% if(obj.hasMore) { %>\r\n  " +
"              <div class=\"row\">\r\n                    <div class=\"col-sm-6\">\r\n   " +
"                     <i style=\"display: inline-block;margin-top: 5px;\">(+<%- obj" +
".hasMore %> see more)</i>\r\n                    </div>\r\n                    <div " +
"class=\"col-sm-6\">\r\n                        <a role=\"button\" class=\"btn btn-prima" +
"ry pull-right\" href=\"<%- obj.url %>/Patients/PatientDetails/<%- obj.patientInfo." +
"id %>/DetailedData/\">See more</a>\r\n                    </div>\r\n                <" +
"/div>\r\n                <% } %>\r\n            </div>\r\n            <div class=\"col-" +
"sm-3\"></div>\r\n        </div>\r\n    </div>\r\n</script>\r\n");

        }
    }
}
#pragma warning restore 1591
