#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Maestro.Web;
    using Maestro.Web.Areas.Site;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Site/Views/Dashboard/Templates/PatientViewDetailsFooter.cshtml")]
    public partial class _Areas_Site_Views_Dashboard_Templates_PatientViewDetailsFooter_cshtml : Maestro.Web.BaseViewPage<dynamic>
    {
        public _Areas_Site_Views_Dashboard_Templates_PatientViewDetailsFooter_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" id=\"patientCardViewTemplateDetailFooter\"");

WriteLiteral(" type=\"text/template\"");

WriteLiteral(@">
    <div class=""patient-alert-detail patient-alert-footer"">
        <div class=""row"">
            <div class=""col-sm-6""></div>
            <div class=""col-sm-3"">
                <!--<a role=""button"" class=""btn btn-primary"" href=""<%- obj.link %>/Patients/PatientDetails/<%- obj.patientId %>/"">Watch Patient</a>-->
            </div>
            <div class=""col-sm-3"">
                <button class=""btn btn-default pull-right acknowledge-all"">Acknowledge all</button>
            </div>
        </div>
    </div>
</script>");

        }
    }
}
#pragma warning restore 1591
