#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Maestro.Web;
    using Maestro.Web.Controls;
    
    #line 1 "..\..\Views\Shared\_CustomerHeader.cshtml"
    using Maestro.Web.Extensions;
    
    #line default
    #line hidden
    using Maestro.Web.Resources;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_CustomerHeader.cshtml")]
    public partial class _Views_Shared__CustomerHeader_cshtml : Maestro.Web.BaseViewPage<dynamic>
    {
        public _Views_Shared__CustomerHeader_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<header");

WriteLiteral(" id=\"header\"");

WriteLiteral(">\r\n    <nav");

WriteLiteral(" class=\"navbar navbar-header-ci\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"navbar-header\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" class=\"navbar-header-logo-ci navbar-brand\"");

WriteAttribute("href", Tuple.Create(" href=\"", 233), Tuple.Create("\"", 340)
            
            #line 7 "..\..\Views\Shared\_CustomerHeader.cshtml"
, Tuple.Create(Tuple.Create("", 240), Tuple.Create<System.Object, System.Int32>(User.Identity.IsAuthenticated ? Url.Action("Index", "Customers", new {area = string.Empty}) : "#"
            
            #line default
            #line hidden
, 240), false)
);

WriteLiteral("></a>\r\n\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"navbar-toggle collapsed\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" data-target=\"#navbar-header-ci-toggle\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">Toggle navigation</span>\r\n                    <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n                    <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n                    <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n                </button>\r\n            </div>\r\n\r\n");

            
            #line 17 "..\..\Views\Shared\_CustomerHeader.cshtml"
            
            
            #line default
            #line hidden
            
            #line 17 "..\..\Views\Shared\_CustomerHeader.cshtml"
             if (User.Identity.IsAuthenticated)
            {

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"navbar-collapse collapse\"");

WriteLiteral(" id=\"navbar-header-ci-toggle\"");

WriteLiteral(">\r\n                    <ul");

WriteLiteral(" class=\"nav navbar-nav navbar-nav-top-ci\"");

WriteLiteral(">\r\n");

            
            #line 21 "..\..\Views\Shared\_CustomerHeader.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 21 "..\..\Views\Shared\_CustomerHeader.cshtml"
                          
                            string dashboardLinkClass = HttpContext.Current.Request.Url.IsRouteMatch("Index", "Dashboard") ? "active" : string.Empty;
                            string patientsLinkClass =
                                HttpContext.Current.Request.Url.IsRouteMatch("Index", "Patients", "Site") ||
                                HttpContext.Current.Request.Url.IsRouteMatch("PatientDetails", "Patients", "Site") ||
                                HttpContext.Current.Request.Url.IsRouteMatch("CreatePatient", "Patients", "Site") ||
                                HttpContext.Current.Request.Url.IsRouteMatch("EditPatient", "Patients", "Site") ?
                                "active" :
                                string.Empty;
                            string careBuilderLinkClass =
                                HttpContext.Current.Request.Url.IsRouteMatch("CareElements", "CareBuilder", "Customer") ||
                                HttpContext.Current.Request.Url.IsRouteMatch("ProtocolsAndPrograms", "CareBuilder", "Customer") ||
                                HttpContext.Current.Request.Url.IsRouteMatch("CreateProtocol", "CareBuilder", "Customer") ||
                                HttpContext.Current.Request.Url.IsRouteMatch("EditProtocol", "CareBuilder", "Customer") ||
                                HttpContext.Current.Request.Url.IsRouteMatch("CreateProgram", "CareBuilder", "Customer") ||
                                HttpContext.Current.Request.Url.IsRouteMatch("EditProgram", "CareBuilder", "Customer") ?
                                "active" :
                                string.Empty;
                        
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 41 "..\..\Views\Shared\_CustomerHeader.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 41 "..\..\Views\Shared\_CustomerHeader.cshtml"
                         if (PagePermissions.IsAvailable("Index", "Dashboard", "Site"))
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <li");

WriteAttribute("class", Tuple.Create(" class=\"", 2862), Tuple.Create("\"", 2889)
            
            #line 43 "..\..\Views\Shared\_CustomerHeader.cshtml"
, Tuple.Create(Tuple.Create("", 2870), Tuple.Create<System.Object, System.Int32>(dashboardLinkClass
            
            #line default
            #line hidden
, 2870), false)
);

WriteLiteral(">\r\n                                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2927), Tuple.Create("\"", 2971)
            
            #line 44 "..\..\Views\Shared\_CustomerHeader.cshtml"
, Tuple.Create(Tuple.Create("", 2934), Tuple.Create<System.Object, System.Int32>(Url.SiteAction("Index", "Dashboard")
            
            #line default
            #line hidden
, 2934), false)
);

WriteLiteral(" class=\"btn btn-link\"");

WriteLiteral(">\r\n                                    <i");

WriteLiteral(" class=\"fa fa-tachometer\"");

WriteLiteral("></i> Dashboard\r\n                                </a>\r\n                          " +
"  </li>\r\n");

            
            #line 48 "..\..\Views\Shared\_CustomerHeader.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 50 "..\..\Views\Shared\_CustomerHeader.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 50 "..\..\Views\Shared\_CustomerHeader.cshtml"
                         if (PagePermissions.IsAvailable("Index", "Patients", "Site"))
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <li");

WriteAttribute("class", Tuple.Create(" class=\"", 3324), Tuple.Create("\"", 3350)
            
            #line 52 "..\..\Views\Shared\_CustomerHeader.cshtml"
, Tuple.Create(Tuple.Create("", 3332), Tuple.Create<System.Object, System.Int32>(patientsLinkClass
            
            #line default
            #line hidden
, 3332), false)
);

WriteLiteral(">\r\n                                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3388), Tuple.Create("\"", 3431)
            
            #line 53 "..\..\Views\Shared\_CustomerHeader.cshtml"
, Tuple.Create(Tuple.Create("", 3395), Tuple.Create<System.Object, System.Int32>(Url.SiteAction("Index", "Patients")
            
            #line default
            #line hidden
, 3395), false)
);

WriteLiteral(" class=\"btn btn-link\"");

WriteLiteral(">\r\n                                    <i");

WriteLiteral(" class=\"fa fa-users\"");

WriteLiteral("></i> Patients\r\n                                </a>\r\n                           " +
" </li>\r\n");

            
            #line 57 "..\..\Views\Shared\_CustomerHeader.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 59 "..\..\Views\Shared\_CustomerHeader.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 59 "..\..\Views\Shared\_CustomerHeader.cshtml"
                         if (PagePermissions.IsAvailable("CareElements", "CareBuilder", "Customer"))
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <li");

WriteAttribute("class", Tuple.Create(" class=\"", 3792), Tuple.Create("\"", 3821)
            
            #line 61 "..\..\Views\Shared\_CustomerHeader.cshtml"
, Tuple.Create(Tuple.Create("", 3800), Tuple.Create<System.Object, System.Int32>(careBuilderLinkClass
            
            #line default
            #line hidden
, 3800), false)
);

WriteLiteral(">\r\n                                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3859), Tuple.Create("\"", 3989)
            
            #line 62 "..\..\Views\Shared\_CustomerHeader.cshtml"
, Tuple.Create(Tuple.Create("", 3866), Tuple.Create<System.Object, System.Int32>(Url.Action("CareElements", "CareBuilder", new {area = "Customer", subdomain = CustomerContext.Current.Customer.Subdomain})
            
            #line default
            #line hidden
, 3866), false)
);

WriteLiteral(" class=\"btn btn-link\"");

WriteLiteral(">\r\n                                    <i");

WriteLiteral(" class=\"fa fa-stethoscope\"");

WriteLiteral("></i> Care Builder\r\n                                </a>\r\n                       " +
"     </li>\r\n");

            
            #line 66 "..\..\Views\Shared\_CustomerHeader.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </ul>\r\n                    <ul");

WriteLiteral(" class=\"nav navbar-nav navbar-nav-user-ci navbar-right\"");

WriteLiteral(">\r\n                        <li");

WriteLiteral(" class=\"dropdown\"");

WriteLiteral(">\r\n                            <a");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(" aria-haspopup=\"true\"");

WriteLiteral(" role=\"button\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" class=\"dropdown-toggle dropdown-toggle-user-ci\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 71 "..\..\Views\Shared\_CustomerHeader.cshtml"
                           Write(GlobalStrings.Layout_Header_Welcome);

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                ");

            
            #line 72 "..\..\Views\Shared\_CustomerHeader.cshtml"
                           Write(User.Identity.Name);

            
            #line default
            #line hidden
WriteLiteral("!\r\n                                <i");

WriteLiteral(" class=\"fa fa-angle-down\"");

WriteLiteral("></i>\r\n                            </a>\r\n                            <ul");

WriteLiteral(" class=\"dropdown-menu\"");

WriteLiteral(">\r\n");

            
            #line 76 "..\..\Views\Shared\_CustomerHeader.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 76 "..\..\Views\Shared\_CustomerHeader.cshtml"
                                 if (PagePermissions.IsAvailable("General", "Settings", "Customer"))
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <li>\r\n                                       " +
" <a");

WriteAttribute("href", Tuple.Create(" href=\"", 5024), Tuple.Create("\"", 5148)
            
            #line 79 "..\..\Views\Shared\_CustomerHeader.cshtml"
, Tuple.Create(Tuple.Create("", 5031), Tuple.Create<System.Object, System.Int32>(Url.Action("General", "Settings", new { area = "Customer", subdomain = CustomerContext.Current.Customer.Subdomain })
            
            #line default
            #line hidden
, 5031), false)
);

WriteLiteral(" class=\"btn btn-link\"");

WriteLiteral(">\r\n                                            Settings\r\n                        " +
"                </a>\r\n                                    </li>\r\n");

            
            #line 83 "..\..\Views\Shared\_CustomerHeader.cshtml"
                                }
                                else if (PagePermissions.IsAvailable("CustomerUsers", "Settings", "Customer"))
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <li>\r\n                                       " +
" <a");

WriteAttribute("href", Tuple.Create(" href=\"", 5582), Tuple.Create("\"", 5712)
            
            #line 87 "..\..\Views\Shared\_CustomerHeader.cshtml"
, Tuple.Create(Tuple.Create("", 5589), Tuple.Create<System.Object, System.Int32>(Url.Action("CustomerUsers", "Settings", new { area = "Customer", subdomain = CustomerContext.Current.Customer.Subdomain })
            
            #line default
            #line hidden
, 5589), false)
);

WriteLiteral(" class=\"btn btn-link\"");

WriteLiteral(">\r\n                                            Settings\r\n                        " +
"                </a>\r\n                                    </li>\r\n");

            
            #line 91 "..\..\Views\Shared\_CustomerHeader.cshtml"
                                }
                                else if (PagePermissions.IsAvailable("ManageThresholds", "Settings", "Customer"))
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <li>\r\n                                       " +
" <a");

WriteAttribute("href", Tuple.Create(" href=\"", 6149), Tuple.Create("\"", 6282)
            
            #line 95 "..\..\Views\Shared\_CustomerHeader.cshtml"
, Tuple.Create(Tuple.Create("", 6156), Tuple.Create<System.Object, System.Int32>(Url.Action("ManageThresholds", "Settings", new { area = "Customer", subdomain = CustomerContext.Current.Customer.Subdomain })
            
            #line default
            #line hidden
, 6156), false)
);

WriteLiteral(" class=\"btn btn-link\"");

WriteLiteral(">\r\n                                            Settings\r\n                        " +
"                </a>\r\n                                    </li>\r\n");

            
            #line 99 "..\..\Views\Shared\_CustomerHeader.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <li>\r\n");

WriteLiteral("                                    ");

            
            #line 102 "..\..\Views\Shared\_CustomerHeader.cshtml"
                               Write(Html.ActionLink(GlobalStrings.Layout_Header_SignOutLink, "Logout", new { controller = "Account", area = string.Empty }, new { @class = "btn btn-link" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </li>\r\n                            </ul>\r\n     " +
"                   </li>\r\n                        ");

WriteLiteral("\r\n                    </ul>\r\n                </div>\r\n");

            
            #line 113 "..\..\Views\Shared\_CustomerHeader.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n    </nav>\r\n</header>");

        }
    }
}
#pragma warning restore 1591
