#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Maestro.Web;
    using Maestro.Web.Controls;
    using Maestro.Web.Resources;
    
    #line 1 "..\..\Views\Shared\_SessionExpirationModal.cshtml"
    using Maestro.Web.Security;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_SessionExpirationModal.cshtml")]
    public partial class _Views_Shared__SessionExpirationModal_cshtml : Maestro.Web.BaseViewPage<dynamic>
    {
        public _Views_Shared__SessionExpirationModal_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<!-- Session timeout in milliseconds-->\r\n<input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"session-timeout\"");

WriteAttribute("value", Tuple.Create(" value=\"", 113), Tuple.Create("\"", 154)
            
            #line 4 "..\..\Views\Shared\_SessionExpirationModal.cshtml"
, Tuple.Create(Tuple.Create("", 121), Tuple.Create<System.Object, System.Int32>(UserContext.ResumeSessionTimeout
            
            #line default
            #line hidden
, 121), false)
);

WriteLiteral("/>\r\n\r\n<div");

WriteLiteral(" class=\"modal fade session-timeout-modal\"");

WriteLiteral(" id=\"session-timeout-modal\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 10 "..\..\Views\Shared\_SessionExpirationModal.cshtml"
           Write(GlobalStrings.SessionExpirationModal_Message);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" id=\"btn-resume-session\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">");

            
            #line 13 "..\..\Views\Shared\_SessionExpirationModal.cshtml"
                                                                                                      Write(GlobalStrings.SessionExpirationModal_ConfirmationButton);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
