#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Maestro.Common.Extensions;
    using Maestro.Web;
    using Maestro.Web.Controls;
    using Maestro.Web.Resources;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Settings/Views/Admins/Index.cshtml")]
    public partial class _Areas_Settings_Views_Admins_Index_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<Maestro.Web.Areas.Settings.Models.Admins.AdminListModel>>
    {
        public _Areas_Settings_Views_Admins_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Settings\Views\Admins\Index.cshtml"
  
    ViewBag.Title = "Administration";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"tab-pane active\"");

WriteLiteral(" id=\"admin-users\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-xs-5\"");

WriteLiteral(">\r\n            <h2");

WriteLiteral(" class=\"ci-page-subheader\"");

WriteLiteral(">");

            
            #line 9 "..\..\Areas\Settings\Views\Admins\Index.cshtml"
                                     Write(GlobalStrings.Settings_Admins_Index_Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"col-sm-7 subhead-add-link\"");

WriteLiteral(">\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 400), Tuple.Create("\"", 438)
            
            #line 13 "..\..\Areas\Settings\Views\Admins\Index.cshtml"
, Tuple.Create(Tuple.Create("", 407), Tuple.Create<System.Object, System.Int32>(Url.Action("Create", "Admins")
            
            #line default
            #line hidden
, 407), false)
);

WriteLiteral(">");

            
            #line 13 "..\..\Areas\Settings\Views\Admins\Index.cshtml"
                                                 Write(GlobalStrings.Settings_Admins_Index_CreateAdminLink);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n        </div>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"ci-admin-list\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" class=\"table\"");

WriteLiteral(">\r\n            <tbody>\r\n");

            
            #line 20 "..\..\Areas\Settings\Views\Admins\Index.cshtml"
                
            
            #line default
            #line hidden
            
            #line 20 "..\..\Areas\Settings\Views\Admins\Index.cshtml"
                 foreach (var admin in Model)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <tr");

WriteAttribute("user-id", Tuple.Create(" user-id=\"", 702), Tuple.Create("\"", 721)
            
            #line 22 "..\..\Areas\Settings\Views\Admins\Index.cshtml"
, Tuple.Create(Tuple.Create("", 712), Tuple.Create<System.Object, System.Int32>(admin.Id
            
            #line default
            #line hidden
, 712), false)
);

WriteLiteral(" role=\"row\"");

WriteLiteral(">\r\n                        <td");

WriteLiteral(" class=\"col-xs-6 ci-user-name\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 24 "..\..\Areas\Settings\Views\Admins\Index.cshtml"
                       Write(admin.FirstName);

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 24 "..\..\Areas\Settings\Views\Admins\Index.cshtml"
                                        Write(admin.LastName);

            
            #line default
            #line hidden
WriteLiteral(" <br />\r\n                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 895), Tuple.Create("\"", 928)
, Tuple.Create(Tuple.Create("", 902), Tuple.Create("mailto:", 902), true)
            
            #line 25 "..\..\Areas\Settings\Views\Admins\Index.cshtml"
, Tuple.Create(Tuple.Create("", 909), Tuple.Create<System.Object, System.Int32>(admin.EmailAddress
            
            #line default
            #line hidden
, 909), false)
);

WriteLiteral(">");

            
            #line 25 "..\..\Areas\Settings\Views\Admins\Index.cshtml"
                                                            Write(admin.EmailAddress);

            
            #line default
            #line hidden
WriteLiteral("</a> <br />\r\n");

WriteLiteral("                            ");

            
            #line 26 "..\..\Areas\Settings\Views\Admins\Index.cshtml"
                       Write(admin.Phone);

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </td>\r\n                        <td");

WriteLiteral(" class=\"col-xs-2\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"label label-success\"");

WriteLiteral(">");

            
            #line 29 "..\..\Areas\Settings\Views\Admins\Index.cshtml"
                                                        Write(admin.Role);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                        </td>\r\n                        <td");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 32 "..\..\Areas\Settings\Views\Admins\Index.cshtml"
                       Write(Html.CheckBox("IsEnabled", admin.IsEnabled, new { @class = "basic-checkbox", data_on_text = "ENABLED", data_off_text = "DISABLED", data_size="mini" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </td>\r\n                        <td");

WriteLiteral(" class=\"col-xs-1\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 35 "..\..\Areas\Settings\Views\Admins\Index.cshtml"
                       Write(Html.ActionLink("Edit", "Edit", "Admins", new { id = admin.Id }, null));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </td>\r\n                    </tr>\r\n");

            
            #line 38 "..\..\Areas\Settings\Views\Admins\Index.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </tbody>\r\n        </table>\r\n    </div>\r\n</div>\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 46 "..\..\Areas\Settings\Views\Admins\Index.cshtml"
Write(Scripts.Render("~/bundles/js/admin-users"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
