// <auto-generated />
namespace HealthLibrary.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class LocalizedValue_RemoveRequirement : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LocalizedValue_RemoveRequirement));
        
        string IMigrationMetadata.Id
        {
            get { return "201507141109320_LocalizedValue_RemoveRequirement"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
