// <auto-generated />
namespace HealthLibrary.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Extend_entities_with_CreatedUTC_and_UpdatedUTC : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Extend_entities_with_CreatedUTC_and_UpdatedUTC));
        
        string IMigrationMetadata.Id
        {
            get { return "201606281154110_Extend_entities_with_CreatedUTC_and_UpdatedUTC"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
