#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Maestro.Common.Extensions;
    using Maestro.Web;
    using Maestro.Web.Areas.Customer;
    using Maestro.Web.Controls;
    using Maestro.Web.Resources;
    
    #line 1 "..\..\Areas\Customer\Views\CareBuilder\Templates\AddQuestionTemplate.cshtml"
    using Roles = Maestro.Domain.Constants.Roles;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Customer/Views/CareBuilder/Templates/AddQuestionTemplate.cshtml")]
    public partial class _Areas_Customer_Views_CareBuilder_Templates_AddQuestionTemplate_cshtml : Maestro.Web.BaseViewPage<dynamic>
    {
        public _Areas_Customer_Views_CareBuilder_Templates_AddQuestionTemplate_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" id=\"addQuestionTemplate\"");

WriteLiteral(" type=\"text/template\"");

WriteLiteral(">\r\n    <div class=\"form-group\">\r\n        <label for=\"careElement-question\">Questi" +
"on</label>\r\n        <textarea name=\"questionElementString.value\"\r\n              " +
"    data-name=\"questionElementString.value\"\r\n                  value=\"<%=questio" +
"nElementString.value%>\"\r\n                  class=\"form-control\"\r\n               " +
"   id=\"careElement-question\"\r\n                  placeholder=\"Enter Question Text" +
" Here\"></textarea>\r\n        <span class=\"help-block hidden\" data-validate-for=\"c" +
"areElement-question\"></span>\r\n    </div>\r\n\r\n    <!-- Audio options -->\r\n    <div" +
" id=\"audio-options-container\">\r\n\r\n    </div>\r\n\r\n    <div class=\"form-group\">\r\n  " +
"      <label>Tags <i>(Optional)</i></label>\r\n        <input type=\"text\" class=\"f" +
"orm-control creation-tags\" data-placeholder=\"Add Tags\" data-loading-placeholder=" +
"\"Loading...\" \r\n               data-name=\"tags\"\r\n               value=\"<%= tags.j" +
"oin(\',\') %>\" />\r\n        <span class=\"help-block help-block-tags hidden\"></span>" +
"\r\n    </div>\r\n    <div class=\"row form-horizontal\">\r\n        <div class=\"col-sm-" +
"6\">\r\n            <div class=\" form-group\">\r\n                <label class=\"col-sm" +
"-3 control-label text-left\">ID:</label>\r\n                <div class=\"col-sm-9\">\r" +
"\n                    <input class=\"form-control\"\r\n                           typ" +
"e=\"text\"\r\n                           name=\"externalId\"\r\n                        " +
"   data-name=\"externalId\"\r\n                           value=\"<%=externalId%>\"\r\n " +
"                          placeholder=\"Enter ID here\" />\r\n                </div>" +
"\r\n            </div>\r\n        </div>\r\n        <div class=\"col-sm-6\">\r\n");

            
            #line 41 "..\..\Areas\Customer\Views\CareBuilder\Templates\AddQuestionTemplate.cshtml"
            
            
            #line default
            #line hidden
            
            #line 41 "..\..\Areas\Customer\Views\CareBuilder\Templates\AddQuestionTemplate.cshtml"
             if (User.IsInRole(Roles.SuperAdmin))
            {

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\" form-group\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" class=\"col-sm-3 control-label text-left\"");

WriteLiteral(">CI ID:</label>\r\n                    <div");

WriteLiteral(" class=\"col-sm-9\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" class=\"form-control\"");

WriteLiteral("\r\n                               type=\"text\"");

WriteLiteral("\r\n                               name=\"internalId\"");

WriteLiteral("\r\n                               data-name=\"internalId\"");

WriteLiteral("\r\n                               value=\"<%=internalId%>\"");

WriteLiteral("\r\n                               placeholder=\"Enter CI ID here\"");

WriteLiteral(" />\r\n                    </div>\r\n                </div>\r\n");

            
            #line 54 "..\..\Areas\Customer\Views\CareBuilder\Templates\AddQuestionTemplate.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral(@"
        </div>
    </div>

    <hr />

    <div class=""form-group js-change-answer-set-row"">
        <button class=""btn btn-default js-change-answer-set"">
            <span class=""glyphicon glyphicon-refresh""></span>
            Change Answer Set
        </button>
    </div>
    <hr class=""js-change-answer-set-row"" />

    <div id=""select-answer-set""></div>

    <div class=""alert alert-success js-alert-create-success hidden"" role=""alert"">Question added successfully</div>
    <div class=""alert alert-success js-alert-update-success hidden"" role=""alert"">Question updated successfully</div>
</script>");

        }
    }
}
#pragma warning restore 1591
