#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Maestro.Common.Extensions;
    using Maestro.Web;
    using Maestro.Web.Areas.Customer;
    using Maestro.Web.Controls;
    using Maestro.Web.Resources;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Customer/Views/CareBuilder/Templates/AnswerSetTypeTemplate.cshtml")]
    public partial class _Areas_Customer_Views_CareBuilder_Templates_AnswerSetTypeTemplate_cshtml : Maestro.Web.BaseViewPage<dynamic>
    {
        public _Areas_Customer_Views_CareBuilder_Templates_AnswerSetTypeTemplate_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" id=\"answerSetTypeTemplate\"");

WriteLiteral(" type=\"text/template\"");

WriteLiteral(@">
<div class=""col-xs-12"">
    <div class=""list-group"">
        <a href=""#"" class=""list-group-item js-add-selection-answer-set"">
            <h4 class=""list-group-item-heading"">Multiple Choice</h4>
            <p class=""list-group-item-text"">Select one of many available answers.</p>
        </a>
        <a href=""#"" class=""list-group-item js-add-scale-answer-set"">
            <h4 class=""list-group-item-heading"">Scale</h4>
            <p class=""list-group-item-text"">Select one of a set of values on a sliding scale.</p>
        </a>
        <!--<a href=""#"" class=""list-group-item"">
            <h4 class=""list-group-item-heading"">Checklist</h4>
            <p class=""list-group-item-text"">Select multiple available answers.</p>
        </a>-->
    </div>
</div>
</script>");

        }
    }
}
#pragma warning restore 1591
