#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Maestro.Common.Extensions;
    using Maestro.Web;
    using Maestro.Web.Areas.Customer;
    using Maestro.Web.Controls;
    using Maestro.Web.Resources;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Customer/Views/CareBuilder/Templates/ChecklistAnswerSetTemplate.cshtml")]
    public partial class _Areas_Customer_Views_CareBuilder_Templates_ChecklistAnswerSetTemplate_cshtml : Maestro.Web.BaseViewPage<dynamic>
    {
        public _Areas_Customer_Views_CareBuilder_Templates_ChecklistAnswerSetTemplate_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" id=\"checkListAnswerSetTemplate\"");

WriteLiteral(" type=\"text/template\"");

WriteLiteral(">\r\n    <div class=\"panel panel-info\">\r\n        <div class=\"panel-heading\" role=\"t" +
"ab\" id=\"answer-headingFour\">\r\n            <h3 class=\"panel-title\">\r\n            " +
"    <a class=\"collapsed panel-toggle\" role=\"button\" data-toggle=\"collapse\" data-" +
"parent=\"#question-accordion\" href=\"#collapse-answer_<%=Id%>\" aria-expanded=\"fals" +
"e\" aria-controls=\"collapse-answer_<%=Id%>\">\r\n                    <%=Name%>\r\n    " +
"            </a>\r\n                <span class=\"pull-right\">\r\n                   " +
" <em>Checklist</em>\r\n                    <a href=\"#\" class=\"js-select-answer-set" +
"\" answer-set-id=\"<%=Id%>\">Select</a>\r\n                </span>\r\n            </h3>" +
"\r\n        </div>\r\n        <div id=\"collapse-answer_<%=Id%>\" class=\"panel-collaps" +
"e collapse\" role=\"tabpanel\">\r\n            <div class=\"panel-body\">\r\n            " +
"    <div class=\"careElement\">\r\n                    <% _.each(SelectionAnswerChoi" +
"ces, function(answerChoice){ %>\r\n\r\n                        <div class=\"checkbox\"" +
">\r\n                            <label for=\"checkbox_001\">\r\n                     " +
"           <input name=\"checkbox_001\" type=\"checkbox\" value=\"\">\r\n               " +
"                 <%=answerChoice.AnswerString.Value%>\r\n                         " +
"   </label>\r\n                        </div>\r\n\r\n                    <% }); %>\r\n  " +
"              </div>\r\n            </div>\r\n            <div class=\"panel-footer\">" +
"\r\n                <div class=\"row careElement\">\r\n                    <% _.each(T" +
"ags, function(tag) { %>\r\n\r\n                    <span class=\"tag btn-link\">\r\n    " +
"                    <span class=\"tag-x cursor-pointer\">\r\n                       " +
"     <span class=\"tag-name\"><%= tag %></span>\r\n                        </span>\r\n" +
"                    </span>\r\n\r\n                    <% }); %>\r\n                </" +
"div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</script>");

        }
    }
}
#pragma warning restore 1591
