#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Maestro.Common.Extensions;
    using Maestro.Web;
    using Maestro.Web.Areas.Customer;
    using Maestro.Web.Controls;
    using Maestro.Web.Resources;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Customer/Views/CareBuilder/Templates/MediaFileTemplate.cshtml")]
    public partial class _Areas_Customer_Views_CareBuilder_Templates_MediaFileTemplate_cshtml : Maestro.Web.BaseViewPage<dynamic>
    {
        public _Areas_Customer_Views_CareBuilder_Templates_MediaFileTemplate_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" id=\"mediaFileTemplate\"");

WriteLiteral(" type=\"text/template\"");

WriteLiteral(">    \r\n    <span class=\"help-block hidden\" data-validate-for=\"media-file-name\"></" +
"span>\r\n    <div class=\"row\">\r\n        <div class=\"col-sm-12\">\r\n            <ul c" +
"lass=\"nav nav-pills nav-pills-info-ci nav-pills-sm-ci nav-tabs-media-ci\">\r\n     " +
"           <li role=\"presentation\" class=\"active\"><a href=\"#media-file\" data-tog" +
"gle=\"tab\">Upload a File</a></li>\r\n                <li role=\"presentation\"><a hre" +
"f=\"#media-link\" data-toggle=\"tab\">Link to a file</a></li>\r\n            </ul>\r\n  " +
"          <div class=\"tab-content\">\r\n                <input type=\"hidden\" name=\"" +
"media.contentType\" id=\"media-content-type\" />\r\n                <input type=\"hidd" +
"en\" data-name=\"media.fileName\" name=\"media.fileName\" id=\"media-file-name\" />\r\n  " +
"              <div class=\"tab-pane active\" id=\"media-file\">\r\n                   " +
" <div class=\"form-group\">\r\n                        <div class=\"input-group input" +
"-group-file-ci\">\r\n                            <input id=\"input-upload-media-name" +
"\" type=\"text\" class=\"form-control\" readonly>\r\n                            <span " +
"class=\"input-group-btn\">\r\n                                <input type=\"file\" id=" +
"\"upload-media-file\" accept=\"application/pdf, image/x-png, image/jpeg, video/mp4\"" +
" >\r\n                                <button type=\"button\" class=\"btn btn-primary" +
" btn-file-ci\" data-loading-text=\"Uploading...\">\r\n                               " +
"     Browse&hellip;\r\n                                </button>\r\n                " +
"            </span>\r\n                        </div>\r\n                        <sp" +
"an class=\"help-block help-block-error help-block-media-fileName hidden\"></span>\r" +
"\n                    </div>\r\n                </div>\r\n                <div class=" +
"\"tab-pane\" id=\"media-link\">\r\n                    <div class=\"form-group\">\r\n     " +
"                   <div class=\"input-group\">\r\n                            <input" +
" type=\"text\" class=\"form-control\" id=\"link-to-media-file\" />\r\n                  " +
"          <span class=\"input-group-btn\">\r\n                                <butto" +
"n class=\"btn btn-primary\" type=\"button\" name=\"uplaod-media-from-link\" id=\"uplaod" +
"-media-from-link\" data-loading-text=\"Uploading...\">Upload</button>\r\n            " +
"                </span>\r\n                        </div>\r\n                       " +
" <span class=\"help-block help-block-error help-block-media-fileName hidden\"></sp" +
"an>\r\n                    </div>\r\n                </div>\r\n            </div>\r\n   " +
"     </div>\r\n    </div>\r\n\r\n    <div id=\"preview-media-container\" class=\"well wel" +
"l-preview-ci hidden\">\r\n        <div class=\"media media-preview-ci\">\r\n           " +
" <div class=\"media-left media-middle\" id=\"preview-media-file\"></div>\r\n          " +
"  <div class=\"media-body\">\r\n                <p id=\"preview-media-file-name\"></p>" +
"\r\n                <a href=\"#\" id=\"remove-media-file-btn\">\r\n                    <" +
"span class=\"glyphicon glyphicon-remove\"></span>\r\n                    Remove\r\n   " +
"             </a>\r\n            </div>\r\n        </div>\r\n    </div>\r\n            \r" +
"\n    <div class=\"form-group\">\r\n        <label for=\"media-name\">Name of Media</la" +
"bel>\r\n        <input type=\"text\" data-name=\"media.name\" name=\"media.name\" class=" +
"\"form-control\" id=\"media-name\" />\r\n        <span class=\"help-block hidden\" data-" +
"validate-for=\"media-name\"></span>\r\n    </div>\r\n\r\n    <div class=\"form-group\">\r\n " +
"       <label for=\"media-content-tags\">Tags <i>(Optional)</i></label>\r\n        <" +
"input type=\"text\" id=\"media-content-tags\" class=\"form-control creation-tags\" dat" +
"a-placeholder=\"Add Tags\" data-loading-placeholder=\"Loading...\" />\r\n    </div>\r\n<" +
"/script>");

        }
    }
}
#pragma warning restore 1591
