#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Maestro.Common.Extensions;
    using Maestro.Web;
    using Maestro.Web.Areas.Customer;
    using Maestro.Web.Controls;
    using Maestro.Web.Resources;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Customer/Views/CareBuilder/Templates/MediaListItemTemplate.cshtml")]
    public partial class _Areas_Customer_Views_CareBuilder_Templates_MediaListItemTemplate_cshtml : Maestro.Web.BaseViewPage<dynamic>
    {
        public _Areas_Customer_Views_CareBuilder_Templates_MediaListItemTemplate_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" id=\"mediaListItemTemplate\"");

WriteLiteral(" type=\"text/template\"");

WriteLiteral(@">
    <div class=""col-md-3"">
        <div class=""thumbnail media-tile media-item"" media-id=""<%=id%>"">
            <% if (contentType.match('image')) { %>
                <% if (thumbnailUrl) { %>
                    <img src=""<%=thumbnailUrl%>"" alt="""">
                <% } else {%>
                    <span class=""glyphicon glyphicon-question-sign""></span>
                <% } %>
            <% } else { %>
                <span class=""glyphicon glyphicon-file""></span>
            <% } %>
            
            <div class=""media-tile-title"" title=""<%=name%>""><%=name%></div>
            <div class=""media-tile-body""><%=mimeTypes[contentType] ? mimeTypes[contentType] : ""Unknown""%></div>
        </div>
    </div>
</script>");

        }
    }
}
#pragma warning restore 1591
