#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Maestro.Common.Extensions;
    using Maestro.Web;
    using Maestro.Web.Areas.Customer;
    using Maestro.Web.Controls;
    using Maestro.Web.Resources;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Customer/Views/CareBuilder/Templates/OpenEndedAnswerSetTemplate.cshtml")]
    public partial class _Areas_Customer_Views_CareBuilder_Templates_OpenEndedAnswerSetTemplate_cshtml : Maestro.Web.BaseViewPage<dynamic>
    {
        public _Areas_Customer_Views_CareBuilder_Templates_OpenEndedAnswerSetTemplate_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" id=\"openEndedAnswerSetTemplate\"");

WriteLiteral(" type=\"text/template\"");

WriteLiteral(@">
    <div class=""panel-heading"" role=""tab"">
        <div class=""clearfix"">
            <h4 class=""panel-title pull-left""><strong><%=name%></strong></h4>
            <div class=""pull-right pull-right-panel-heading-ci"">
                <a href=""#"" class=""btn btn-primary btn-sm js-select-answer-set"" answer-set-id=""<%=id%>"">Select</a>
            </div>
        </div>
    </div>
    <div class=""panel-footer"">
        <div class=""row"">
            <div class=""col-sm-7""></div>
            <div class=""col-sm-5 text-right"">
                <small>
                    <strong>Default Language:</strong> EN-US
                </small>
            </div>
        </div>
    </div>
</script>");

        }
    }
}
#pragma warning restore 1591
