#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Maestro.Common.Extensions;
    using Maestro.Web;
    using Maestro.Web.Areas.Customer;
    using Maestro.Web.Controls;
    using Maestro.Web.Resources;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Customer/Views/CareBuilder/Templates/ScaleAnswerSetTemplate.cshtml")]
    public partial class _Areas_Customer_Views_CareBuilder_Templates_ScaleAnswerSetTemplate_cshtml : Maestro.Web.BaseViewPage<dynamic>
    {
        public _Areas_Customer_Views_CareBuilder_Templates_ScaleAnswerSetTemplate_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" id=\"ScaleAnswerSetTemplate\"");

WriteLiteral(" type=\"text/template\"");

WriteLiteral(">\r\n    <div class=\"panel-heading\" role=\"tab\" id=\"heading_<%=id%>\">\r\n        <div " +
"class=\"clearfix\">   \r\n            <h4 class=\"panel-title pull-left\">\r\n          " +
"      <a class=\"collapsed panel-toggle\" \r\n                    role=\"button\" \r\n  " +
"                  data-toggle=\"collapse\" \r\n                    data-parent=\"#que" +
"stion-accordion\" \r\n                    href=\"#collapse-answer_<%=id%>\" \r\n       " +
"             aria-expanded=\"true\" \r\n                    aria-controls=\"collapse-" +
"answer_<%=id%>\">\r\n                    <small>Scale:</small>\r\n                   " +
" <strong><%=name%></strong>\r\n                </a>\r\n            </h4>\r\n          " +
"  <div class=\"pull-right pull-right-panel-heading-ci\">                      \r\n  " +
"              <a href=\"#\" class=\"btn btn-primary btn-sm js-select-answer-set\" an" +
"swer-set-id=\"<%=id%>\">Select</a>\r\n            </div>\r\n        </div>\r\n    </div>" +
"\r\n\r\n    <div id=\"collapse-answer_<%=id%>\" class=\"panel-collapse collapse\" role=\"" +
"tabpanel\" aria-labelledby=\"heading_<%=id%>\">\r\n        <div class=\"panel-body\">\r\n" +
"            <div class=\"js-scale-control\"></div>\r\n        </div>\r\n    </div>\r\n  " +
"  <div class=\"panel-footer\">\r\n        <div class=\"row\">\r\n            <div class=" +
"\"col-sm-7\">\r\n                <strong>\r\n                    <small>Tags:</small>\r" +
"\n                </strong>\r\n                <% _.each(tags, function(tag) { %>\r\n" +
"                    <span class=\"label label-info\"><%= tag %></span>\r\n          " +
"      <% }); %>\r\n            </div>\r\n            <div class=\"col-sm-5 text-right" +
"\">\r\n                <small>\r\n                    <strong>Default Language:</stro" +
"ng> EN-US\r\n                </small>\r\n            </div>\r\n\r\n        </div>\r\n    <" +
"/div>\r\n</script>");

        }
    }
}
#pragma warning restore 1591
