#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Maestro.Common.Extensions;
    using Maestro.Web;
    using Maestro.Web.Areas.Customer;
    using Maestro.Web.Controls;
    using Maestro.Web.Resources;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Customer/Views/CareBuilder/Templates/ScaleAnswersControlTemplate.cshtml")]
    public partial class _Areas_Customer_Views_CareBuilder_Templates_ScaleAnswersControlTemplate_cshtml : Maestro.Web.BaseViewPage<dynamic>
    {
        public _Areas_Customer_Views_CareBuilder_Templates_ScaleAnswersControlTemplate_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" id=\"scaleAnswersControlTemplate\"");

WriteLiteral(" type=\"text/template\"");

WriteLiteral(@">
    <div class=""row"">
        <div class=""col-sm-8 col-sm-offset-2 js-scale-answers"">
            <div class=""row"">
                <div class=""col-sm-1""></div>
                <div class=""col-sm-10 offset-0"">
                    <div class=""clearfix"">
                        <% if (lowLabel !== null) { %>
                            <span class=""pull-left scale-answer-label min""><%=lowLabel.value%></span>
                        <% } %>
                        <% if (highLabel !== null) { %>
                            <span class=""pull-right scale-answer-label max""><%=highLabel.value%></span>
                        <% } %>
                        <% if (midLabel !== null) { %>
                            <span class=""pull-center scale-answer-label mid""><%=midLabel.value%></span>
                        <% } %>
                    </div>
                </div>
                <div class=""col-sm-1""></div>
            </div>
            <div class=""row"">
                <div class=""col-sm-1 text-right""><%=lowValue%></div>
                <div class=""col-sm-10 offset-0"">
                    <input class=""scale"" type=""text"" data-slider-min=""<%=lowValue%>"" data-slider-max=""<%=highValue%>"" data-slider-step=""1"" data-slider-value=""0"" />
                </div>
                <div class=""col-sm-1""><%=highValue%></div>
            </div>
        </div>
    </div>
</script>");

        }
    }
}
#pragma warning restore 1591
