#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Maestro.Common.Extensions;
    using Maestro.Web;
    using Maestro.Web.Areas.Customer;
    using Maestro.Web.Controls;
    using Maestro.Web.Resources;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Customer/Views/CareBuilder/Templates/SelectAnswerSetTemplate.cshtml")]
    public partial class _Areas_Customer_Views_CareBuilder_Templates_SelectAnswerSetTemplate_cshtml : Maestro.Web.BaseViewPage<dynamic>
    {
        public _Areas_Customer_Views_CareBuilder_Templates_SelectAnswerSetTemplate_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" id=\"selectAnswerSetTemplate\"");

WriteLiteral(" type=\"text/template\"");

WriteLiteral(">\r\n    \r\n    <div class=\"clearfix\">\r\n        <h4 class=\"pull-left\">Answers</h4>\r\n" +
"        <!--<a class=\"btn btn-primary btn-default btn-sm pull-right\" href=\"#answ" +
"ers-createNew\" aria-controls=\"createNew\" role=\"tab\" data-toggle=\"tab\">Create New" +
"</a>-->\r\n    </div>\r\n\r\n    <!-- Tab panes -->\r\n    \r\n    <div class=\"tab-content" +
"\">\r\n        <div role=\"tabpanel\" class=\"tab-pane active\" id=\"answers-library\">\r\n" +
"            <div class=\"well well-sm\">\r\n                <div class=\"row\">\r\n     " +
"               <div class=\"col-sm-4\">\r\n                        <select class=\"fo" +
"rm-control\" id=\"answer-type\">\r\n                            <option value=\"All\">A" +
"ll</option>\r\n                            <option value=\"SelectionAnswerSet\">Mult" +
"iple Choice</option>\r\n                            <!--<option value=\"SelectionAn" +
"swerSet\">Check List</option>-->\r\n                            <option value=\"Scal" +
"eAnswerSet\">Scale Answer Set</option>\r\n                            <option value" +
"=\"OpenEndedAnswerSet\">Open Ended Answer Set</option>\r\n                        </" +
"select>\r\n                    </div>\r\n                     <div class=\"col-sm-4\">" +
"\r\n                        <div class=\"input-group\">\r\n                           " +
" <select id=\"search-tags\" data-placeholder=\"Search by Tags\" data-loading-placeho" +
"lder=\"Loading...\" class=\"form-control chosen-select searching-tags\"></select>\r\n " +
"                           <span class=\"input-group-btn\">\r\n                     " +
"           <button class=\"btn btn-default js-search-clear\" type=\"button\">\r\n     " +
"                               <span class=\"glyphicon glyphicon-remove\"></span>\r" +
"\n                                </button>\r\n                            </span>\r" +
"\n                        </div>\r\n                    </div>\r\n                   " +
" <div class=\" col-sm-4\">\r\n                        <input type=\"text\" class=\"form" +
"-control\" id=\"search-keyword\" placeholder=\"Enter Keyword Here\">\r\n               " +
"     </div>\r\n                </div>\r\n            </div>\r\n\r\n            <div clas" +
"s=\"row\">\r\n                <div class=\"col-sm-12\">\r\n                    <div clas" +
"s=\"panel-group panel-group-ci\" id=\"question-accordion\" role=\"tablist\" aria-multi" +
"selectable=\"true\"></div>\r\n                </div>\r\n            </div>\r\n        </" +
"div>\r\n        <div role=\"tabpanel\" class=\"tab-pane\" id=\"answers-createNew\">\r\n   " +
"         <div class=\"row\">\r\n                <div class=\"col-xs-12\">\r\n           " +
"         <div class=\"well\">\r\n                        <h5>Select answer set type:" +
"</h5>\r\n                        <div class=\"list-group\">\r\n                       " +
"     <a href=\"#\" class=\"list-group-item\"><h5 class=\"list-group-item-heading bold" +
"\">Multiple Choice</h5><p class=\"list-group-item-text\">Select one of many availab" +
"le answers.</p></a>\r\n                            <a href=\"#\" class=\"list-group-i" +
"tem\"><h5 class=\"list-group-item-heading\">Scale</h5><p class=\"list-group-item-tex" +
"t\">Select one of a set of values on a sliding scale.</p></a>\r\n                  " +
"          <a href=\"#\" class=\"list-group-item\"><h5 class=\"list-group-item-heading" +
"\">Open Ended</h5><p class=\"list-group-item-text\">Free text entry, up to 500 char" +
"acters.</p></a>\r\n                            <a href=\"#\" class=\"list-group-item\"" +
"><h5 class=\"list-group-item-heading\">Checklist</h5><p class=\"list-group-item-tex" +
"t\">Select multiple available answers.</p></a>\r\n                        </div>\r\n " +
"                   </div>\r\n                </div>\r\n            </div>\r\n        <" +
"/div>\r\n    </div>\r\n</script>");

        }
    }
}
#pragma warning restore 1591
