#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Maestro.Common.Extensions;
    
    #line 1 "..\..\Areas\Customer\Views\CareBuilder\Templates\TextMediaElementListItemTemplate.cshtml"
    using Maestro.Domain.Enums;
    
    #line default
    #line hidden
    using Maestro.Web;
    using Maestro.Web.Areas.Customer;
    using Maestro.Web.Controls;
    using Maestro.Web.Resources;
    
    #line 2 "..\..\Areas\Customer\Views\CareBuilder\Templates\TextMediaElementListItemTemplate.cshtml"
    using Roles = Maestro.Domain.Constants.Roles;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Customer/Views/CareBuilder/Templates/TextMediaElementListItemTemplate.csh" +
        "tml")]
    public partial class _Areas_Customer_Views_CareBuilder_Templates_TextMediaElementListItemTemplate_cshtml : Maestro.Web.BaseViewPage<dynamic>
    {
        public _Areas_Customer_Views_CareBuilder_Templates_TextMediaElementListItemTemplate_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<script");

WriteLiteral(" id=\"textMediaElementListItemTemplate\"");

WriteLiteral(" type=\"text/template\"");

WriteLiteral(@">
    <div class=""panel-heading clearfix"" role=""tab"" id=""heading-<%= id %>"">
        <input type=""hidden"" value=""<%= id %>"" name=""Id"" />
        <div class=""row"">
            <div class=""col-sm-10"">
                <h4 class=""panel-title strong"">
                    <a role=""button""
                       class=""js-collapsed collapsed panel-toggle""
                       data-toggle=""collapse""
                       data-parent=""#care-elements-list""
                       href=""#collapse-<%=id%>""
                       aria-expanded=""false""
                       aria-controls=""collapse-<%=id%>"">
                        <%= name %>
                    </a>
                </h4>
            </div>
            <div class=""col-sm-2 small italic text-right"">Text and Media</div>
        </div>

        <% _.each(tags, function(tag){ %>
        <span class=""label label-info""><%= tag %></span>
        <% }); %>

    </div>
    <div id=""collapse-<%=id%>"" class=""panel-collapse collapse"" role=""tabpanel"" aria-labelledby=""heading-<%=id%>"">
        <div class=""panel-body"">
            <div class=""text-media-text""></div>
            <div class=""text-media-media""></div>
        </div>
        <div class=""panel-footer clearfix"">
            <div class=""pull-left"">
                <strong>Default Language:</strong> EN-US
            </div>
            
");

            
            #line 39 "..\..\Areas\Customer\Views\CareBuilder\Templates\TextMediaElementListItemTemplate.cshtml"
            
            
            #line default
            #line hidden
            
            #line 39 "..\..\Areas\Customer\Views\CareBuilder\Templates\TextMediaElementListItemTemplate.cshtml"
             if (User.IsInRoles(Roles.SuperAdmin) || User.HasPermissions(CustomerContext.Current.Customer.Id, CustomerUserRolePermissions.ManageCareElements))
            {

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"pull-right pull-right-panel-heading-ci\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"btn-group\"");

WriteLiteral(">\r\n                        <!--<a href=\"#modal-usageReport\" class=\"btn btn-defaul" +
"t\" data-target=\"#modal-usageReport\" data-toggle=\"modal\">View Usage Report</a>-->" +
"\r\n                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"btn btn-primary js-edit-text-media-element\"");

WriteLiteral(">Edit</a>\r\n                    </div>\r\n                </div>\r\n");

            
            #line 47 "..\..\Areas\Customer\Views\CareBuilder\Templates\TextMediaElementListItemTemplate.cshtml"
            }            

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n    </div>\r\n</script>");

        }
    }
}
#pragma warning restore 1591
