#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Maestro.Common.Extensions;
    using Maestro.Web;
    using Maestro.Web.Areas.Customer;
    using Maestro.Web.Controls;
    using Maestro.Web.Resources;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Customer/Views/CareBuilder/Templates/TextMediaElementTemplate.cshtml")]
    public partial class _Areas_Customer_Views_CareBuilder_Templates_TextMediaElementTemplate_cshtml : Maestro.Web.BaseViewPage<dynamic>
    {
        public _Areas_Customer_Views_CareBuilder_Templates_TextMediaElementTemplate_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" id=\"textMediaElementTemplate\"");

WriteLiteral(" type=\"text/template\"");

WriteLiteral(">\r\n    <div class=\"form-group\">\r\n        <label>Language</label>\r\n        <div>EN" +
"-US (default)</div>\r\n    </div>\r\n\r\n    <div class=\"form-group\">\r\n        <label " +
"for=\"careElement-textelementName\">Name of Content Item</label>\r\n        <input d" +
"ata-name=\"name\" name=\"name\" value=\"<%= name %>\" type=\"text\" class=\"form-control\"" +
" id=\"careElement-textelementName\" placeholder=\"Enter Name Here\">\r\n        <span " +
"class=\"help-block hidden\" data-validate-for=\"careElement-textelementName\"></span" +
">\r\n    </div>\r\n\r\n    <div class=\"form-group\">\r\n        <label>Tags <i>(Optional)" +
"</i></label>\r\n        <input type=\"text\" id=\"text-and-media-element-tags\" class=" +
"\"form-control creation-tags\" \r\n               data-placeholder=\"Add Tags\" \r\n    " +
"           data-loading-placeholder=\"Loading...\" \r\n               data-name=\"tag" +
"s\"\r\n               value=\"<%= tags.join(\',\') %>\" />\r\n        <span class=\"help-b" +
"lock help-block-tags hidden\" data-validate-for=\"text-and-media-element-tags\"></s" +
"pan>\r\n    </div>\r\n\r\n    <div class=\"form-group\">\r\n        <label for=\"careElemen" +
"t-TextElementString\">Text <i>(Optional)</i></label>\r\n        <textarea class=\"fo" +
"rm-control\" data-name=\"text.value\" name=\"text.value\" id=\"careElement-textelement" +
"Text\"><%= text.value %></textarea>\r\n        <span class=\"help-block hidden\" data" +
"-validate-for=\"careElement-textelementText\"></span>\r\n    </div>\r\n\r\n    <div id=\"" +
"audio-options\">\r\n\r\n    </div>\r\n\r\n    <div class=\"js-media-preview\">\r\n\r\n        <" +
"div class=\"media media-preview-ci\">\r\n            <div class=\"media-preview media" +
"-left media-middle\"></div>\r\n            <div class=\"media-body media-buttons\"></" +
"div>\r\n        </div>\r\n\r\n    </div>\r\n\r\n    <div class=\"form-group\" id=\"js-media-f" +
"orm-container\"></div>\r\n\r\n    <div class=\"alert alert-success js-alert-create-suc" +
"cess hidden\" role=\"alert\">Text & Media element added successfully!</div>\r\n    <d" +
"iv class=\"alert alert-success js-alert-update-success hidden\" role=\"alert\">Text " +
"& Media element updated successfully!</div>\r\n    <div class=\"alert alert-danger " +
"hidden\" role=\"alert\"></div>\r\n</script>");

        }
    }
}
#pragma warning restore 1591
