#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
    using Maestro.Domain.Constants;
    
    #line default
    #line hidden
    using Maestro.Web;
    using Maestro.Web.Areas.Site;
    
    #line 2 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
    using Newtonsoft.Json;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Site/Views/Patients/Templates.cshtml")]
    public partial class _Areas_Site_Views_Patients_Templates_cshtml : Maestro.Web.BaseViewPage<dynamic>
    {
        public _Areas_Site_Views_Patients_Templates_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 6 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
  
    ViewBag.AppId = "appPatients";

    var constants = Model != null ? JsonConvert.SerializeObject(Model) : string.Empty;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<input");

WriteLiteral(" id=\"constants\"");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("value", Tuple.Create(" value=\"", 247), Tuple.Create("\"", 265)
            
            #line 12 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
, Tuple.Create(Tuple.Create("", 255), Tuple.Create<System.Object, System.Int32>(constants
            
            #line default
            #line hidden
, 255), false)
);

WriteLiteral("/>\r\n\r\n");

            
            #line 14 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Hidden("user-manage-permission", (@User.IsInCustomerRoles(CustomerUserRoles.CustomerAdmin) || @User.IsInCustomerRoles(CustomerUserRoles.ManageAllPatients))));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" id=\"patients-container\"");

WriteLiteral(" class=\"content-container-ci\"");

WriteLiteral(">\r\n    <img");

WriteLiteral(" src=\"/Content/img/spinner.gif\"");

WriteLiteral(" class=\"spinner\"");

WriteLiteral(">\r\n</div>\r\n\r\n");

            
            #line 20 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("~/Areas/Site/Views/Notes/_Templates.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 22 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/PatientDetails/Dashboard/PatientDashboardTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 23 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/PatientDetails/Dashboard/PatientDashboardHealthSessionsViewTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 24 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/PatientDetails/Dashboard/PatientDashboardThresholdsViewTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 25 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/PatientDetails/Dashboard/PatientDashboardPeripheralsViewTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 27 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/PatientsListTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 28 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/PatientsListItemTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 29 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/PatientViewTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 30 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/PatientCalendarTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 31 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/PatientCalendarSearchListItemTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 32 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/PatientCalendarProgramModalTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 33 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/PatientCalendarProgramTerminateModalTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 34 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/PatientCalendarProgramDeleteModalTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 35 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/PatientHealthSessionContainerTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 36 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/PatientHealthSessionRecurringRulesTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 37 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/PatientDashboardViewTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 38 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/PatientDetailedDataViewTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 39 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/PatientTrendsViewTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 40 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/PatientTrendsDaterangeViewTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 41 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/PatientTrendsVitalChartViewTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 42 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/PatientTrendsBloodPressureChartViewTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 43 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/PatientTrendsAssessmentChartViewTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 44 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/PatientTrendsAssessmentAnswerFlyoutTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 45 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/PatientTrendsAddChartsViewTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 46 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/PatientTrendsVitalReadingFlyoutTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 47 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/PatientTrendsVitalThresholdFlyoutTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 48 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/PatientHistoryViewTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 49 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/PatientCreateTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 50 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/PatientEditTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 51 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/PatientCareManagersAssignedListItemTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 52 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/PatientMeasurementTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 53 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/CareManagersListItemTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 54 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/CareManagersAssignedListItemTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 55 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/ConditionsListItemTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 56 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/ConditionsAssignedListItemTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 58 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/ConditionDetailsTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 59 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/ConditionDetailsContentTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 60 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/NoProgramsFoundView"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 61 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/NoProtocolsFoundView"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 62 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/ProgramListItemTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 63 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/ProtocolListItemTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 65 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/DevicesListItemTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 66 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/DevicesConfirmRemoveTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 67 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/DevicesConfirmDecomissionTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 68 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/DevicesConfirmAddTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 69 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/DevicesIVRErrorTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 70 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/DevicesManagePinTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 71 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/DevicesSelectListItemTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 72 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/DeviceSingleItemTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 73 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/ModalLgTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 74 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/PatientSearchBoxTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 75 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/PatientSearchBoxItemTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 76 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/PatientCalendarHistoryTemplates"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 77 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/PatientsListItemDetailsTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 78 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/WaitTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 79 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/PatientSearchBoxAdvancedTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 80 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/PatientSearchBoxAdvancedItemTemplate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 81 "..\..\Areas\Site\Views\Patients\Templates.cshtml"
Write(Html.Partial("Templates/OneWayChatTemplate"));

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
