#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Maestro.Web;
    using Maestro.Web.Areas.Site;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Site/Views/Notes/Templates/NoteItemTemplate.cshtml")]
    public partial class _Areas_Site_Views_Notes_Templates_NoteItemTemplate_cshtml : Maestro.Web.BaseViewPage<dynamic>
    {
        public _Areas_Site_Views_Notes_Templates_NoteItemTemplate_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" id=\"notesItemTemplate\"");

WriteLiteral(" type=\"text/template\"");

WriteLiteral(">\r\n    <time class=\"note-block-time\" datetime=\"<%- obj.CreatedUtc %>\"><%- obj.cre" +
"atedUtcFormated %></time>\r\n    <h4 class=\"note-block-notables\"><% var notablesLe" +
"ngth = obj.notables.length; if(notablesLength) { %>\r\n        <% _.each(obj.notab" +
"les, function(notable, index) { %>\r\n        <%- notable %><% if(index !== notabl" +
"esLength -1) { %>, <% } %>\r\n        <% }); %>\r\n        <% } %>\r\n    </h4>\r\n    <" +
"% if(obj.createdBy) { %>\r\n    <div class=\"note-block-author\">\r\n        <strong s" +
"tyle=\"color: #555; padding-bottom: 10px; display: inline-block;\">\r\n            <" +
"%- obj.createdBy %>\r\n        </strong>\r\n    </div>\r\n    <% } %>\r\n    <% if(obj.m" +
"easurement) { %>\r\n    <div class=\"measurement\" style=\"padding-bottom: 10px;\">\r\n " +
"       <span style=\"color: <%- obj.measurement.color %>\">\r\n            <% if(!ob" +
"j.measurement.isAutomated) { %>*<% } %><%- obj.measurement.value %> <%- obj.meas" +
"urement.unit %>\r\n        </span>\r\n        on <i><%- obj.measurement.date %> on <" +
"%- obj.measurement.time %></i>\r\n    </div>\r\n    <% } %>\r\n    <% if(obj.measureme" +
"ntReading) { %>\r\n    <div class=\"measurement\" style=\"padding-bottom: 10px;\">\r\n  " +
"      <% if(!obj.measurementReading.isAutomated) { %>*<% } %>\r\n        <% if (ob" +
"j.measurementReading.vitals && obj.measurementReading.vitals.length) { %>\r\n\r\n   " +
"         <% _.each(obj.measurementReading.vitals, function (vital, index) { %>\r\n" +
"                <% if (index > 0) { %>,<% } %>\r\n                <%- vital.name %" +
">\r\n                <span style=\"color: <%= vital.color %>\">\r\n                   " +
" <%- vital.value %> <%- vital.unit %>\r\n                </span>\r\n            <% }" +
"); %>\r\n\r\n        <% } %>\r\n        on <i><%- obj.measurementReading.date %> <%- o" +
"bj.measurementReading.time %></i>\r\n    </div>\r\n    <% } %>\r\n    <% if(obj.behavi" +
"or) { %>\r\n    <div class=\"behavior\" style=\"padding-bottom: 10px;\">\r\n        <str" +
"ong><%- obj.behavior.question %> -\r\n            <span style=\"color: <%- obj.beha" +
"vior.color %>\">\r\n                \r\n                <% _.each(obj.behavior.answer" +
"s, function(answer, index) {%>\r\n                    <%- answer %>\r\n             " +
"       <% if (index != obj.behavior.answers.length - 1) {%> , <% } %>\r\n         " +
"       <% }) %>\r\n\r\n                <!--<%- obj.behavior.answer %>-->\r\n          " +
"  </span>\r\n        </strong>\r\n        on <i><%- obj.behavior.date %> <%- obj.beh" +
"avior.time %></i>\r\n    </div>\r\n    <% } %>\r\n    <div class=\"note-block-text\">\r\n " +
"       <div class=\"note-block-full-text\">\r\n            <%- obj.text %>\r\n        " +
"</div>\r\n    </div>\r\n</script>");

        }
    }
}
#pragma warning restore 1591
