#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Maestro.Common.Extensions;
    using Maestro.Web;
    using Maestro.Web.Areas.Customer;
    using Maestro.Web.Controls;
    using Maestro.Web.Resources;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Customer/Views/Sites/_Selector.cshtml")]
    public partial class _Areas_Customer_Views_Sites__Selector_cshtml : Maestro.Web.BaseViewPage<Maestro.Web.Areas.Customer.Models.Sites.SitesSelectorViewModel>
    {
        public _Areas_Customer_Views_Sites__Selector_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" id=\"site-selector\"");

WriteLiteral(" class=\"panel panel-default visible\"");

WriteLiteral(">\r\n    <header");

WriteLiteral(" class=\"panel-heading stylized-panel collapsed\"");

WriteLiteral(" style=\"cursor: pointer;\"");

WriteLiteral("\r\n            data-toggle=\"collapse\"");

WriteLiteral("\r\n            aria-controls=\"assigned-sites\"");

WriteLiteral("\r\n            data-target=\"#assigned-sites\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n");

            
            #line 9 "..\..\Areas\Customer\Views\Sites\_Selector.cshtml"
            
            
            #line default
            #line hidden
            
            #line 9 "..\..\Areas\Customer\Views\Sites\_Selector.cshtml"
             if (Model.AvailableSites.Any()) {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"col-sm-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 11 "..\..\Areas\Customer\Views\Sites\_Selector.cshtml"
           Write(Model.CurrentSiteName);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"col-sm-2\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"caret-icon pull-right\"");

WriteLiteral("></span>\r\n            </div>\r\n");

            
            #line 16 "..\..\Areas\Customer\Views\Sites\_Selector.cshtml"
            } else {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 18 "..\..\Areas\Customer\Views\Sites\_Selector.cshtml"
           Write(Model.CurrentSiteName);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");

            
            #line 20 "..\..\Areas\Customer\Views\Sites\_Selector.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n    </header>\r\n\r\n");

            
            #line 24 "..\..\Areas\Customer\Views\Sites\_Selector.cshtml"
    
            
            #line default
            #line hidden
            
            #line 24 "..\..\Areas\Customer\Views\Sites\_Selector.cshtml"
     if (Model.AvailableSites.Any())
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" id=\"assigned-sites\"");

WriteLiteral(" class=\"panel-collapse collapse\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"panel-body no-padding\"");

WriteLiteral(">\r\n                <ul");

WriteLiteral(" class=\"list-unstyled\"");

WriteLiteral(">\r\n");

            
            #line 29 "..\..\Areas\Customer\Views\Sites\_Selector.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 29 "..\..\Areas\Customer\Views\Sites\_Selector.cshtml"
                     foreach (var site in Model.AvailableSites)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1123), Tuple.Create("\"", 1203)
            
            #line 31 "..\..\Areas\Customer\Views\Sites\_Selector.cshtml"
, Tuple.Create(Tuple.Create("", 1130), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Dashboard", new { siteId = site.Id, area = "Site"})
            
            #line default
            #line hidden
, 1130), false)
);

WriteLiteral(">");

            
            #line 31 "..\..\Areas\Customer\Views\Sites\_Selector.cshtml"
                                                                                                           Write(site.Name);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 32 "..\..\Areas\Customer\Views\Sites\_Selector.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </ul>\r\n            </div>\r\n        </div>\r\n");

            
            #line 36 "..\..\Areas\Customer\Views\Sites\_Selector.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>");

        }
    }
}
#pragma warning restore 1591
