// <auto-generated />
namespace MessagingHub.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ExtendApplicationwithNotifcationPortprop : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ExtendApplicationwithNotifcationPortprop));
        
        string IMigrationMetadata.Id
        {
            get { return "201602241057031_Extend Application with NotifcationPort prop"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
