//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VitalsService.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VitalsService.Domain.Resources.GlobalStrings", typeof(GlobalStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert severity with such id does not exist.
        /// </summary>
        internal static string AlertResult_AlertSeverityWithSuchIdDoesNotExist {
            get {
                return ResourceManager.GetString("AlertResult_AlertSeverityWithSuchIdDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of provided alerts doesn&apos;t exist or already acknowledged.
        /// </summary>
        internal static string AlertResult_OneOfProvidedAlertsDoesNotExistOrAlreadyAcknowledged {
            get {
                return ResourceManager.GetString("AlertResult_OneOfProvidedAlertsDoesNotExistOrAlreadyAcknowledged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert severity not found.
        /// </summary>
        internal static string AlertSeverityResult_NotFound {
            get {
                return ResourceManager.GetString("AlertSeverityResult_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string AlertSeverityResult_Success {
            get {
                return ResourceManager.GetString("AlertSeverityResult_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment media already uploaded.
        /// </summary>
        internal static string AssessmentMedia_FileAlreadyUploadedError {
            get {
                return ResourceManager.GetString("AssessmentMedia_FileAlreadyUploadedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect file format.
        /// </summary>
        internal static string AssessmentMedia_InvalidContentProvidedError {
            get {
                return ResourceManager.GetString("AssessmentMedia_InvalidContentProvidedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment media not found.
        /// </summary>
        internal static string AssessmentMedia_NotFoundError {
            get {
                return ResourceManager.GetString("AssessmentMedia_NotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition with such name aleary exists for that customer id..
        /// </summary>
        internal static string ConditionsStatus_ConditionAlreadyExistsForThatCustomer {
            get {
                return ResourceManager.GetString("ConditionsStatus_ConditionAlreadyExistsForThatCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition not found.
        /// </summary>
        internal static string ConditionsStatus_ConditionNotFound {
            get {
                return ResourceManager.GetString("ConditionsStatus_ConditionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of provided conditions is invalid.
        /// </summary>
        internal static string CreateUpdatePatientConditionsStatus_OneOfProvidedConditionsInvalid {
            get {
                return ResourceManager.GetString("CreateUpdatePatientConditionsStatus_OneOfProvidedConditionsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than {1}.
        /// </summary>
        internal static string GreaterThanAttribute_ValidationError {
            get {
                return ResourceManager.GetString("GreaterThanAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect assessment media id.
        /// </summary>
        internal static string HealthSession_AssessmentMediaIsNotValid {
            get {
                return ResourceManager.GetString("HealthSession_AssessmentMediaIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health session with such ClientId already exists.
        /// </summary>
        internal static string HealthSession_HealthSessionWithClientIdAlreadyExists {
            get {
                return ResourceManager.GetString("HealthSession_HealthSessionWithClientIdAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health session not found.
        /// </summary>
        internal static string HealthSession_NotFound {
            get {
                return ResourceManager.GetString("HealthSession_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string HealthSession_Success {
            get {
                return ResourceManager.GetString("HealthSession_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement with such ClientId already exists.
        /// </summary>
        internal static string Measurement_MeasurementWithClientIdAlreadyExists {
            get {
                return ResourceManager.GetString("Measurement_MeasurementWithClientIdAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided HealthSessionElement&apos;s identifier is incorrect.
        /// </summary>
        internal static string NoteStatus_HealthSessionElementConflict {
            get {
                return ResourceManager.GetString("NoteStatus_HealthSessionElementConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided Measurement&apos;s identifier is incorrect.
        /// </summary>
        internal static string NoteStatus_MeasurementConflict {
            get {
                return ResourceManager.GetString("NoteStatus_MeasurementConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note with such identifier doesn&apos;t exist.
        /// </summary>
        internal static string NoteStatus_NotFound {
            get {
                return ResourceManager.GetString("NoteStatus_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notable with such name already exists.
        /// </summary>
        internal static string SuggestedNotableStatus_NameConflict {
            get {
                return ResourceManager.GetString("SuggestedNotableStatus_NameConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notable with such identifier doesn&apos;t exist.
        /// </summary>
        internal static string SuggestedNotableStatus_NotFound {
            get {
                return ResourceManager.GetString("SuggestedNotableStatus_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert severity sith such identifier doesn&apos;t exist.
        /// </summary>
        internal static string ThresholdResult_AlertSeverityDoesNotExist {
            get {
                return ResourceManager.GetString("ThresholdResult_AlertSeverityDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified condition does not exist.
        /// </summary>
        internal static string ThresholdResult_ConditionDoesNotExist {
            get {
                return ResourceManager.GetString("ThresholdResult_ConditionDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition should be specified..
        /// </summary>
        internal static string ThresholdResult_ConditionShouldBeSpecified {
            get {
                return ResourceManager.GetString("ThresholdResult_ConditionShouldBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Alert Severity should be used (if at least one Alert Severity is being used within Customer).
        /// </summary>
        internal static string ThresholdResult_ExistingAlertSeverityShouldBeUsed {
            get {
                return ResourceManager.GetString("ThresholdResult_ExistingAlertSeverityShouldBeUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string ThresholdResult_Success {
            get {
                return ResourceManager.GetString("ThresholdResult_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold with such identifier doesn&apos;t exist.
        /// </summary>
        internal static string ThresholdResult_ThresholdWithSuchIdDoesNotExist {
            get {
                return ResourceManager.GetString("ThresholdResult_ThresholdWithSuchIdDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold for this Vital, Severity and Condition already exists.
        /// </summary>
        internal static string ThresholdResult_VitalConditionThresholdAlreadyExists {
            get {
                return ResourceManager.GetString("ThresholdResult_VitalConditionThresholdAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold for this Vital already exists.
        /// </summary>
        internal static string ThresholdResult_VitalThresholdAlreadyExists {
            get {
                return ResourceManager.GetString("ThresholdResult_VitalThresholdAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold for this Vital doesn&apos;t exist.
        /// </summary>
        internal static string ThresholdResult_VitalThresholdDoesNotExist {
            get {
                return ResourceManager.GetString("ThresholdResult_VitalThresholdDoesNotExist", resourceCulture);
            }
        }
    }
}
