#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Maestro.Web;
    using Maestro.Web.Controls;
    using Maestro.Web.Resources;
    using Postal;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Emails/ResetPassword.cshtml")]
    public partial class _Views_Emails_ResetPassword_cshtml : Maestro.Web.BaseViewPage<Maestro.Web.Models.Emails.ResetPasswordEmail>
    {
        public _Views_Emails_ResetPassword_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("To: ");

            
            #line 2 "..\..\Views\Emails\ResetPassword.cshtml"
Write(Model.To);

            
            #line default
            #line hidden
WriteLiteral("\r\nFrom: info@careinnovations.com\r\nSubject: Reset Password\r\n<!DOCTYPE html>\r\n<html" +
">\r\n<head>\r\n    <meta");

WriteLiteral(" http-equiv=\"Content-Type\"");

WriteLiteral(" content=\"text/html; charset=UTF-8\"");

WriteLiteral(" />\r\n    <head />\r\n    <body>\r\n        <table");

WriteLiteral(" width=\"580\"");

WriteLiteral(" align=\"centered\"");

WriteLiteral(" border=\"0\"");

WriteLiteral(" cellpadding=\"10\"");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(">\r\n            <tr>\r\n                <td");

WriteLiteral(" width=\"560\"");

WriteLiteral(" align=\"centered\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" style=\"width: 100%; margin: 0 auto; font-family: sans-serif; font-size: 16px; li" +
"ne-height: 22px;\"");

WriteLiteral(">\r\n                        Dear ");

            
            #line 15 "..\..\Views\Emails\ResetPassword.cshtml"
                        Write(Model.UserName);

            
            #line default
            #line hidden
WriteLiteral(@",
       
                        <br />
                        <br />
                        As requested, here is a link to reset your password. If you did not make this request, you may contact us at 1-855-885-2273 (CARE)<br />
                        <br />
");

WriteLiteral("                        ");

            
            #line 21 "..\..\Views\Emails\ResetPassword.cshtml"
                   Write(Model.ConfirmationLink);

            
            #line default
            #line hidden
WriteLiteral(@"<br />
                        <br />
                        You will be asked to set up a password.<br />
                        <br />
                        Sincerely,<br />
                        The Health Harmony Team<br />
                        Intel-GE Care Innovations&#8482;<br />
                        Address: 3721 Douglas Blvd., Suite 100, Roseville, CA 95661
                        <br />
                    </div>
                </td>
            </tr>
        </table>
    </body>
</html>
");

        }
    }
}
#pragma warning restore 1591
